/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delete Prescription</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ase.queryDsl.DeletePrescription#getWhereprescription <em>Whereprescription</em>}</li>
 * </ul>
 *
 * @see ase.queryDsl.QueryDslPackage#getDeletePrescription()
 * @model
 * @generated
 */
public interface DeletePrescription extends Delete
{
  /**
   * Returns the value of the '<em><b>Whereprescription</b></em>' containment reference list.
   * The list contents are of type {@link ase.queryDsl.WherePrescription}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Whereprescription</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Whereprescription</em>' containment reference list.
   * @see ase.queryDsl.QueryDslPackage#getDeletePrescription_Whereprescription()
   * @model containment="true"
   * @generated
   */
  EList<WherePrescription> getWhereprescription();

} // DeletePrescription
