/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delete Patient Monitoring</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ase.queryDsl.DeletePatientMonitoring#getWherepatientMonitoring <em>Wherepatient Monitoring</em>}</li>
 * </ul>
 *
 * @see ase.queryDsl.QueryDslPackage#getDeletePatientMonitoring()
 * @model
 * @generated
 */
public interface DeletePatientMonitoring extends Delete
{
  /**
   * Returns the value of the '<em><b>Wherepatient Monitoring</b></em>' containment reference list.
   * The list contents are of type {@link ase.queryDsl.WherePatientMonitoring}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Wherepatient Monitoring</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wherepatient Monitoring</em>' containment reference list.
   * @see ase.queryDsl.QueryDslPackage#getDeletePatientMonitoring_WherepatientMonitoring()
   * @model containment="true"
   * @generated
   */
  EList<WherePatientMonitoring> getWherepatientMonitoring();

} // DeletePatientMonitoring
