/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Drop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ase.queryDsl.Drop#getTable_name <em>Table name</em>}</li>
 * </ul>
 *
 * @see ase.queryDsl.QueryDslPackage#getDrop()
 * @model
 * @generated
 */
public interface Drop extends QueryType
{
  /**
   * Returns the value of the '<em><b>Table name</b></em>' attribute list.
   * The list contents are of type {@link ase.queryDsl.TableName}.
   * The literals are from the enumeration {@link ase.queryDsl.TableName}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Table name</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table name</em>' attribute list.
   * @see ase.queryDsl.TableName
   * @see ase.queryDsl.QueryDslPackage#getDrop_Table_name()
   * @model unique="false"
   * @generated
   */
  EList<TableName> getTable_name();

} // Drop
