/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Insert Medical Record</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ase.queryDsl.InsertMedicalRecord#getRecordId <em>Record Id</em>}</li>
 *   <li>{@link ase.queryDsl.InsertMedicalRecord#getPatientId <em>Patient Id</em>}</li>
 *   <li>{@link ase.queryDsl.InsertMedicalRecord#getDoctorId <em>Doctor Id</em>}</li>
 *   <li>{@link ase.queryDsl.InsertMedicalRecord#getMedicalCondition <em>Medical Condition</em>}</li>
 *   <li>{@link ase.queryDsl.InsertMedicalRecord#getDate <em>Date</em>}</li>
 *   <li>{@link ase.queryDsl.InsertMedicalRecord#getPrice <em>Price</em>}</li>
 *   <li>{@link ase.queryDsl.InsertMedicalRecord#getDescription <em>Description</em>}</li>
 * </ul>
 *
 * @see ase.queryDsl.QueryDslPackage#getInsertMedicalRecord()
 * @model
 * @generated
 */
public interface InsertMedicalRecord extends Insert
{
  /**
   * Returns the value of the '<em><b>Record Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Record Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Record Id</em>' attribute.
   * @see #setRecordId(int)
   * @see ase.queryDsl.QueryDslPackage#getInsertMedicalRecord_RecordId()
   * @model
   * @generated
   */
  int getRecordId();

  /**
   * Sets the value of the '{@link ase.queryDsl.InsertMedicalRecord#getRecordId <em>Record Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Record Id</em>' attribute.
   * @see #getRecordId()
   * @generated
   */
  void setRecordId(int value);

  /**
   * Returns the value of the '<em><b>Patient Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Patient Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Patient Id</em>' attribute.
   * @see #setPatientId(int)
   * @see ase.queryDsl.QueryDslPackage#getInsertMedicalRecord_PatientId()
   * @model
   * @generated
   */
  int getPatientId();

  /**
   * Sets the value of the '{@link ase.queryDsl.InsertMedicalRecord#getPatientId <em>Patient Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Patient Id</em>' attribute.
   * @see #getPatientId()
   * @generated
   */
  void setPatientId(int value);

  /**
   * Returns the value of the '<em><b>Doctor Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Doctor Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Doctor Id</em>' attribute.
   * @see #setDoctorId(int)
   * @see ase.queryDsl.QueryDslPackage#getInsertMedicalRecord_DoctorId()
   * @model
   * @generated
   */
  int getDoctorId();

  /**
   * Sets the value of the '{@link ase.queryDsl.InsertMedicalRecord#getDoctorId <em>Doctor Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Doctor Id</em>' attribute.
   * @see #getDoctorId()
   * @generated
   */
  void setDoctorId(int value);

  /**
   * Returns the value of the '<em><b>Medical Condition</b></em>' attribute.
   * The literals are from the enumeration {@link ase.queryDsl.MedicalCondition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Medical Condition</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Medical Condition</em>' attribute.
   * @see ase.queryDsl.MedicalCondition
   * @see #setMedicalCondition(MedicalCondition)
   * @see ase.queryDsl.QueryDslPackage#getInsertMedicalRecord_MedicalCondition()
   * @model
   * @generated
   */
  MedicalCondition getMedicalCondition();

  /**
   * Sets the value of the '{@link ase.queryDsl.InsertMedicalRecord#getMedicalCondition <em>Medical Condition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Medical Condition</em>' attribute.
   * @see ase.queryDsl.MedicalCondition
   * @see #getMedicalCondition()
   * @generated
   */
  void setMedicalCondition(MedicalCondition value);

  /**
   * Returns the value of the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Date</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Date</em>' attribute.
   * @see #setDate(String)
   * @see ase.queryDsl.QueryDslPackage#getInsertMedicalRecord_Date()
   * @model
   * @generated
   */
  String getDate();

  /**
   * Sets the value of the '{@link ase.queryDsl.InsertMedicalRecord#getDate <em>Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Date</em>' attribute.
   * @see #getDate()
   * @generated
   */
  void setDate(String value);

  /**
   * Returns the value of the '<em><b>Price</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Price</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Price</em>' attribute.
   * @see #setPrice(String)
   * @see ase.queryDsl.QueryDslPackage#getInsertMedicalRecord_Price()
   * @model
   * @generated
   */
  String getPrice();

  /**
   * Sets the value of the '{@link ase.queryDsl.InsertMedicalRecord#getPrice <em>Price</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Price</em>' attribute.
   * @see #getPrice()
   * @generated
   */
  void setPrice(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see ase.queryDsl.QueryDslPackage#getInsertMedicalRecord_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link ase.queryDsl.InsertMedicalRecord#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

} // InsertMedicalRecord
