/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Insert</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ase.queryDsl.QueryDslPackage#getInsert()
 * @model
 * @generated
 */
public interface Insert extends QueryType
{
} // Insert
