/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Insert Patient Monitoring</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ase.queryDsl.InsertPatientMonitoring#getMonitoringId <em>Monitoring Id</em>}</li>
 *   <li>{@link ase.queryDsl.InsertPatientMonitoring#getPatientId <em>Patient Id</em>}</li>
 *   <li>{@link ase.queryDsl.InsertPatientMonitoring#getCategory <em>Category</em>}</li>
 *   <li>{@link ase.queryDsl.InsertPatientMonitoring#getDate <em>Date</em>}</li>
 *   <li>{@link ase.queryDsl.InsertPatientMonitoring#getRiskPerception <em>Risk Perception</em>}</li>
 *   <li>{@link ase.queryDsl.InsertPatientMonitoring#getTreadted <em>Treadted</em>}</li>
 *   <li>{@link ase.queryDsl.InsertPatientMonitoring#getDeviceId <em>Device Id</em>}</li>
 * </ul>
 *
 * @see ase.queryDsl.QueryDslPackage#getInsertPatientMonitoring()
 * @model
 * @generated
 */
public interface InsertPatientMonitoring extends Insert
{
  /**
   * Returns the value of the '<em><b>Monitoring Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Monitoring Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Monitoring Id</em>' attribute.
   * @see #setMonitoringId(int)
   * @see ase.queryDsl.QueryDslPackage#getInsertPatientMonitoring_MonitoringId()
   * @model
   * @generated
   */
  int getMonitoringId();

  /**
   * Sets the value of the '{@link ase.queryDsl.InsertPatientMonitoring#getMonitoringId <em>Monitoring Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Monitoring Id</em>' attribute.
   * @see #getMonitoringId()
   * @generated
   */
  void setMonitoringId(int value);

  /**
   * Returns the value of the '<em><b>Patient Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Patient Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Patient Id</em>' attribute.
   * @see #setPatientId(int)
   * @see ase.queryDsl.QueryDslPackage#getInsertPatientMonitoring_PatientId()
   * @model
   * @generated
   */
  int getPatientId();

  /**
   * Sets the value of the '{@link ase.queryDsl.InsertPatientMonitoring#getPatientId <em>Patient Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Patient Id</em>' attribute.
   * @see #getPatientId()
   * @generated
   */
  void setPatientId(int value);

  /**
   * Returns the value of the '<em><b>Category</b></em>' attribute.
   * The literals are from the enumeration {@link ase.queryDsl.MedicalCondition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Category</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Category</em>' attribute.
   * @see ase.queryDsl.MedicalCondition
   * @see #setCategory(MedicalCondition)
   * @see ase.queryDsl.QueryDslPackage#getInsertPatientMonitoring_Category()
   * @model
   * @generated
   */
  MedicalCondition getCategory();

  /**
   * Sets the value of the '{@link ase.queryDsl.InsertPatientMonitoring#getCategory <em>Category</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Category</em>' attribute.
   * @see ase.queryDsl.MedicalCondition
   * @see #getCategory()
   * @generated
   */
  void setCategory(MedicalCondition value);

  /**
   * Returns the value of the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Date</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Date</em>' attribute.
   * @see #setDate(String)
   * @see ase.queryDsl.QueryDslPackage#getInsertPatientMonitoring_Date()
   * @model
   * @generated
   */
  String getDate();

  /**
   * Sets the value of the '{@link ase.queryDsl.InsertPatientMonitoring#getDate <em>Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Date</em>' attribute.
   * @see #getDate()
   * @generated
   */
  void setDate(String value);

  /**
   * Returns the value of the '<em><b>Risk Perception</b></em>' attribute.
   * The literals are from the enumeration {@link ase.queryDsl.RiskPerception}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Risk Perception</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Risk Perception</em>' attribute.
   * @see ase.queryDsl.RiskPerception
   * @see #setRiskPerception(RiskPerception)
   * @see ase.queryDsl.QueryDslPackage#getInsertPatientMonitoring_RiskPerception()
   * @model
   * @generated
   */
  RiskPerception getRiskPerception();

  /**
   * Sets the value of the '{@link ase.queryDsl.InsertPatientMonitoring#getRiskPerception <em>Risk Perception</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Risk Perception</em>' attribute.
   * @see ase.queryDsl.RiskPerception
   * @see #getRiskPerception()
   * @generated
   */
  void setRiskPerception(RiskPerception value);

  /**
   * Returns the value of the '<em><b>Treadted</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Treadted</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Treadted</em>' attribute.
   * @see #setTreadted(String)
   * @see ase.queryDsl.QueryDslPackage#getInsertPatientMonitoring_Treadted()
   * @model
   * @generated
   */
  String getTreadted();

  /**
   * Sets the value of the '{@link ase.queryDsl.InsertPatientMonitoring#getTreadted <em>Treadted</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Treadted</em>' attribute.
   * @see #getTreadted()
   * @generated
   */
  void setTreadted(String value);

  /**
   * Returns the value of the '<em><b>Device Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Device Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Device Id</em>' attribute.
   * @see #setDeviceId(int)
   * @see ase.queryDsl.QueryDslPackage#getInsertPatientMonitoring_DeviceId()
   * @model
   * @generated
   */
  int getDeviceId();

  /**
   * Sets the value of the '{@link ase.queryDsl.InsertPatientMonitoring#getDeviceId <em>Device Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Device Id</em>' attribute.
   * @see #getDeviceId()
   * @generated
   */
  void setDeviceId(int value);

} // InsertPatientMonitoring
