/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see ase.queryDsl.QueryDslPackage
 * @generated
 */
public interface QueryDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  QueryDslFactory eINSTANCE = ase.queryDsl.impl.QueryDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Query Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Query Type</em>'.
   * @generated
   */
  QueryType createQueryType();

  /**
   * Returns a new object of class '<em>Select</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Select</em>'.
   * @generated
   */
  Select createSelect();

  /**
   * Returns a new object of class '<em>Select Medical Record</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Select Medical Record</em>'.
   * @generated
   */
  SelectMedicalRecord createSelectMedicalRecord();

  /**
   * Returns a new object of class '<em>Select Patient Monitoring</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Select Patient Monitoring</em>'.
   * @generated
   */
  SelectPatientMonitoring createSelectPatientMonitoring();

  /**
   * Returns a new object of class '<em>Select Prescription</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Select Prescription</em>'.
   * @generated
   */
  SelectPrescription createSelectPrescription();

  /**
   * Returns a new object of class '<em>Insert</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Insert</em>'.
   * @generated
   */
  Insert createInsert();

  /**
   * Returns a new object of class '<em>Insert Medical Record</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Insert Medical Record</em>'.
   * @generated
   */
  InsertMedicalRecord createInsertMedicalRecord();

  /**
   * Returns a new object of class '<em>Insert Patient Monitoring</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Insert Patient Monitoring</em>'.
   * @generated
   */
  InsertPatientMonitoring createInsertPatientMonitoring();

  /**
   * Returns a new object of class '<em>Insert Prescription</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Insert Prescription</em>'.
   * @generated
   */
  InsertPrescription createInsertPrescription();

  /**
   * Returns a new object of class '<em>Drop</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Drop</em>'.
   * @generated
   */
  Drop createDrop();

  /**
   * Returns a new object of class '<em>Delete</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Delete</em>'.
   * @generated
   */
  Delete createDelete();

  /**
   * Returns a new object of class '<em>Delete Medical Record</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Delete Medical Record</em>'.
   * @generated
   */
  DeleteMedicalRecord createDeleteMedicalRecord();

  /**
   * Returns a new object of class '<em>Delete Patient Monitoring</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Delete Patient Monitoring</em>'.
   * @generated
   */
  DeletePatientMonitoring createDeletePatientMonitoring();

  /**
   * Returns a new object of class '<em>Delete Prescription</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Delete Prescription</em>'.
   * @generated
   */
  DeletePrescription createDeletePrescription();

  /**
   * Returns a new object of class '<em>Where Medical Record</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Where Medical Record</em>'.
   * @generated
   */
  WhereMedicalRecord createWhereMedicalRecord();

  /**
   * Returns a new object of class '<em>Where Patient Monitoring</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Where Patient Monitoring</em>'.
   * @generated
   */
  WherePatientMonitoring createWherePatientMonitoring();

  /**
   * Returns a new object of class '<em>Where Prescription</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Where Prescription</em>'.
   * @generated
   */
  WherePrescription createWherePrescription();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  QueryDslPackage getQueryDslPackage();

} //QueryDslFactory
