/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see ase.queryDsl.QueryDslFactory
 * @model kind="package"
 * @generated
 */
public interface QueryDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "queryDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.QueryDsl.ase";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "queryDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  QueryDslPackage eINSTANCE = ase.queryDsl.impl.QueryDslPackageImpl.init();

  /**
   * The meta object id for the '{@link ase.queryDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.impl.ModelImpl
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Query Type</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__QUERY_TYPE = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ase.queryDsl.impl.QueryTypeImpl <em>Query Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.impl.QueryTypeImpl
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getQueryType()
   * @generated
   */
  int QUERY_TYPE = 1;

  /**
   * The number of structural features of the '<em>Query Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link ase.queryDsl.impl.SelectImpl <em>Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.impl.SelectImpl
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getSelect()
   * @generated
   */
  int SELECT = 2;

  /**
   * The number of structural features of the '<em>Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_FEATURE_COUNT = QUERY_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ase.queryDsl.impl.SelectMedicalRecordImpl <em>Select Medical Record</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.impl.SelectMedicalRecordImpl
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getSelectMedicalRecord()
   * @generated
   */
  int SELECT_MEDICAL_RECORD = 3;

  /**
   * The feature id for the '<em><b>Variable Medical Record</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_MEDICAL_RECORD__VARIABLE_MEDICAL_RECORD = SELECT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Variable Medical Record Next</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_MEDICAL_RECORD__VARIABLE_MEDICAL_RECORD_NEXT = SELECT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Where</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_MEDICAL_RECORD__WHERE = SELECT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Select Medical Record</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_MEDICAL_RECORD_FEATURE_COUNT = SELECT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link ase.queryDsl.impl.SelectPatientMonitoringImpl <em>Select Patient Monitoring</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.impl.SelectPatientMonitoringImpl
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getSelectPatientMonitoring()
   * @generated
   */
  int SELECT_PATIENT_MONITORING = 4;

  /**
   * The feature id for the '<em><b>Variable Patient Monitoring</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_PATIENT_MONITORING__VARIABLE_PATIENT_MONITORING = SELECT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Variable Patient Monitoring Next</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_PATIENT_MONITORING__VARIABLE_PATIENT_MONITORING_NEXT = SELECT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Where</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_PATIENT_MONITORING__WHERE = SELECT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Select Patient Monitoring</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_PATIENT_MONITORING_FEATURE_COUNT = SELECT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link ase.queryDsl.impl.SelectPrescriptionImpl <em>Select Prescription</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.impl.SelectPrescriptionImpl
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getSelectPrescription()
   * @generated
   */
  int SELECT_PRESCRIPTION = 5;

  /**
   * The feature id for the '<em><b>Variable Prescription</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_PRESCRIPTION__VARIABLE_PRESCRIPTION = SELECT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Variable Prescription Next</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_PRESCRIPTION__VARIABLE_PRESCRIPTION_NEXT = SELECT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Where</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_PRESCRIPTION__WHERE = SELECT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Select Prescription</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_PRESCRIPTION_FEATURE_COUNT = SELECT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link ase.queryDsl.impl.InsertImpl <em>Insert</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.impl.InsertImpl
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getInsert()
   * @generated
   */
  int INSERT = 6;

  /**
   * The number of structural features of the '<em>Insert</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_FEATURE_COUNT = QUERY_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ase.queryDsl.impl.InsertMedicalRecordImpl <em>Insert Medical Record</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.impl.InsertMedicalRecordImpl
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getInsertMedicalRecord()
   * @generated
   */
  int INSERT_MEDICAL_RECORD = 7;

  /**
   * The feature id for the '<em><b>Record Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_MEDICAL_RECORD__RECORD_ID = INSERT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Patient Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_MEDICAL_RECORD__PATIENT_ID = INSERT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Doctor Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_MEDICAL_RECORD__DOCTOR_ID = INSERT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Medical Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_MEDICAL_RECORD__MEDICAL_CONDITION = INSERT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_MEDICAL_RECORD__DATE = INSERT_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Price</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_MEDICAL_RECORD__PRICE = INSERT_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_MEDICAL_RECORD__DESCRIPTION = INSERT_FEATURE_COUNT + 6;

  /**
   * The number of structural features of the '<em>Insert Medical Record</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_MEDICAL_RECORD_FEATURE_COUNT = INSERT_FEATURE_COUNT + 7;

  /**
   * The meta object id for the '{@link ase.queryDsl.impl.InsertPatientMonitoringImpl <em>Insert Patient Monitoring</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.impl.InsertPatientMonitoringImpl
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getInsertPatientMonitoring()
   * @generated
   */
  int INSERT_PATIENT_MONITORING = 8;

  /**
   * The feature id for the '<em><b>Monitoring Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_PATIENT_MONITORING__MONITORING_ID = INSERT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Patient Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_PATIENT_MONITORING__PATIENT_ID = INSERT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Category</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_PATIENT_MONITORING__CATEGORY = INSERT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_PATIENT_MONITORING__DATE = INSERT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Risk Perception</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_PATIENT_MONITORING__RISK_PERCEPTION = INSERT_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Treadted</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_PATIENT_MONITORING__TREADTED = INSERT_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Device Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_PATIENT_MONITORING__DEVICE_ID = INSERT_FEATURE_COUNT + 6;

  /**
   * The number of structural features of the '<em>Insert Patient Monitoring</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_PATIENT_MONITORING_FEATURE_COUNT = INSERT_FEATURE_COUNT + 7;

  /**
   * The meta object id for the '{@link ase.queryDsl.impl.InsertPrescriptionImpl <em>Insert Prescription</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.impl.InsertPrescriptionImpl
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getInsertPrescription()
   * @generated
   */
  int INSERT_PRESCRIPTION = 9;

  /**
   * The feature id for the '<em><b>Prescription Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_PRESCRIPTION__PRESCRIPTION_ID = INSERT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Record Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_PRESCRIPTION__RECORD_ID = INSERT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Medication Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_PRESCRIPTION__MEDICATION_NAME = INSERT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_PRESCRIPTION__START = INSERT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_PRESCRIPTION__END = INSERT_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Ordered</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_PRESCRIPTION__ORDERED = INSERT_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Price</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_PRESCRIPTION__PRICE = INSERT_FEATURE_COUNT + 6;

  /**
   * The number of structural features of the '<em>Insert Prescription</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_PRESCRIPTION_FEATURE_COUNT = INSERT_FEATURE_COUNT + 7;

  /**
   * The meta object id for the '{@link ase.queryDsl.impl.DropImpl <em>Drop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.impl.DropImpl
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getDrop()
   * @generated
   */
  int DROP = 10;

  /**
   * The feature id for the '<em><b>Table name</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROP__TABLE_NAME = QUERY_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Drop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROP_FEATURE_COUNT = QUERY_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ase.queryDsl.impl.DeleteImpl <em>Delete</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.impl.DeleteImpl
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getDelete()
   * @generated
   */
  int DELETE = 11;

  /**
   * The number of structural features of the '<em>Delete</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE_FEATURE_COUNT = QUERY_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ase.queryDsl.impl.DeleteMedicalRecordImpl <em>Delete Medical Record</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.impl.DeleteMedicalRecordImpl
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getDeleteMedicalRecord()
   * @generated
   */
  int DELETE_MEDICAL_RECORD = 12;

  /**
   * The feature id for the '<em><b>Where Medical Record</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE_MEDICAL_RECORD__WHERE_MEDICAL_RECORD = DELETE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Delete Medical Record</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE_MEDICAL_RECORD_FEATURE_COUNT = DELETE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ase.queryDsl.impl.DeletePatientMonitoringImpl <em>Delete Patient Monitoring</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.impl.DeletePatientMonitoringImpl
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getDeletePatientMonitoring()
   * @generated
   */
  int DELETE_PATIENT_MONITORING = 13;

  /**
   * The feature id for the '<em><b>Wherepatient Monitoring</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE_PATIENT_MONITORING__WHEREPATIENT_MONITORING = DELETE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Delete Patient Monitoring</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE_PATIENT_MONITORING_FEATURE_COUNT = DELETE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ase.queryDsl.impl.DeletePrescriptionImpl <em>Delete Prescription</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.impl.DeletePrescriptionImpl
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getDeletePrescription()
   * @generated
   */
  int DELETE_PRESCRIPTION = 14;

  /**
   * The feature id for the '<em><b>Whereprescription</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE_PRESCRIPTION__WHEREPRESCRIPTION = DELETE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Delete Prescription</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE_PRESCRIPTION_FEATURE_COUNT = DELETE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ase.queryDsl.impl.WhereMedicalRecordImpl <em>Where Medical Record</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.impl.WhereMedicalRecordImpl
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getWhereMedicalRecord()
   * @generated
   */
  int WHERE_MEDICAL_RECORD = 15;

  /**
   * The feature id for the '<em><b>Record Id</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_MEDICAL_RECORD__RECORD_ID = 0;

  /**
   * The feature id for the '<em><b>Patient Id</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_MEDICAL_RECORD__PATIENT_ID = 1;

  /**
   * The feature id for the '<em><b>Doctor Id</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_MEDICAL_RECORD__DOCTOR_ID = 2;

  /**
   * The feature id for the '<em><b>Medical Condition</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_MEDICAL_RECORD__MEDICAL_CONDITION = 3;

  /**
   * The feature id for the '<em><b>Date</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_MEDICAL_RECORD__DATE = 4;

  /**
   * The feature id for the '<em><b>Price</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_MEDICAL_RECORD__PRICE = 5;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_MEDICAL_RECORD__DESCRIPTION = 6;

  /**
   * The number of structural features of the '<em>Where Medical Record</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_MEDICAL_RECORD_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link ase.queryDsl.impl.WherePatientMonitoringImpl <em>Where Patient Monitoring</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.impl.WherePatientMonitoringImpl
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getWherePatientMonitoring()
   * @generated
   */
  int WHERE_PATIENT_MONITORING = 16;

  /**
   * The feature id for the '<em><b>Monitoring Id</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_PATIENT_MONITORING__MONITORING_ID = 0;

  /**
   * The feature id for the '<em><b>Patient Id</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_PATIENT_MONITORING__PATIENT_ID = 1;

  /**
   * The feature id for the '<em><b>Category</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_PATIENT_MONITORING__CATEGORY = 2;

  /**
   * The feature id for the '<em><b>Date</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_PATIENT_MONITORING__DATE = 3;

  /**
   * The feature id for the '<em><b>Riskperception</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_PATIENT_MONITORING__RISKPERCEPTION = 4;

  /**
   * The feature id for the '<em><b>Treated</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_PATIENT_MONITORING__TREATED = 5;

  /**
   * The feature id for the '<em><b>Device Id</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_PATIENT_MONITORING__DEVICE_ID = 6;

  /**
   * The number of structural features of the '<em>Where Patient Monitoring</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_PATIENT_MONITORING_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link ase.queryDsl.impl.WherePrescriptionImpl <em>Where Prescription</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.impl.WherePrescriptionImpl
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getWherePrescription()
   * @generated
   */
  int WHERE_PRESCRIPTION = 17;

  /**
   * The feature id for the '<em><b>Prescription Id</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_PRESCRIPTION__PRESCRIPTION_ID = 0;

  /**
   * The feature id for the '<em><b>Record Id</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_PRESCRIPTION__RECORD_ID = 1;

  /**
   * The feature id for the '<em><b>Medication Name</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_PRESCRIPTION__MEDICATION_NAME = 2;

  /**
   * The feature id for the '<em><b>Start</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_PRESCRIPTION__START = 3;

  /**
   * The feature id for the '<em><b>End</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_PRESCRIPTION__END = 4;

  /**
   * The feature id for the '<em><b>Ordered</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_PRESCRIPTION__ORDERED = 5;

  /**
   * The feature id for the '<em><b>Price</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_PRESCRIPTION__PRICE = 6;

  /**
   * The number of structural features of the '<em>Where Prescription</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_PRESCRIPTION_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link ase.queryDsl.TableName <em>Table Name</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.TableName
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getTableName()
   * @generated
   */
  int TABLE_NAME = 18;

  /**
   * The meta object id for the '{@link ase.queryDsl.VariableMedicalRecord <em>Variable Medical Record</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.VariableMedicalRecord
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getVariableMedicalRecord()
   * @generated
   */
  int VARIABLE_MEDICAL_RECORD = 19;

  /**
   * The meta object id for the '{@link ase.queryDsl.VariablePatientMonitoring <em>Variable Patient Monitoring</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.VariablePatientMonitoring
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getVariablePatientMonitoring()
   * @generated
   */
  int VARIABLE_PATIENT_MONITORING = 20;

  /**
   * The meta object id for the '{@link ase.queryDsl.VariablePrescription <em>Variable Prescription</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.VariablePrescription
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getVariablePrescription()
   * @generated
   */
  int VARIABLE_PRESCRIPTION = 21;

  /**
   * The meta object id for the '{@link ase.queryDsl.MedicalCondition <em>Medical Condition</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.MedicalCondition
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getMedicalCondition()
   * @generated
   */
  int MEDICAL_CONDITION = 22;

  /**
   * The meta object id for the '{@link ase.queryDsl.RiskPerception <em>Risk Perception</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ase.queryDsl.RiskPerception
   * @see ase.queryDsl.impl.QueryDslPackageImpl#getRiskPerception()
   * @generated
   */
  int RISK_PERCEPTION = 23;


  /**
   * Returns the meta object for class '{@link ase.queryDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see ase.queryDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link ase.queryDsl.Model#getQueryType <em>Query Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Query Type</em>'.
   * @see ase.queryDsl.Model#getQueryType()
   * @see #getModel()
   * @generated
   */
  EReference getModel_QueryType();

  /**
   * Returns the meta object for class '{@link ase.queryDsl.QueryType <em>Query Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Query Type</em>'.
   * @see ase.queryDsl.QueryType
   * @generated
   */
  EClass getQueryType();

  /**
   * Returns the meta object for class '{@link ase.queryDsl.Select <em>Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select</em>'.
   * @see ase.queryDsl.Select
   * @generated
   */
  EClass getSelect();

  /**
   * Returns the meta object for class '{@link ase.queryDsl.SelectMedicalRecord <em>Select Medical Record</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select Medical Record</em>'.
   * @see ase.queryDsl.SelectMedicalRecord
   * @generated
   */
  EClass getSelectMedicalRecord();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.SelectMedicalRecord#getVariableMedicalRecord <em>Variable Medical Record</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Variable Medical Record</em>'.
   * @see ase.queryDsl.SelectMedicalRecord#getVariableMedicalRecord()
   * @see #getSelectMedicalRecord()
   * @generated
   */
  EAttribute getSelectMedicalRecord_VariableMedicalRecord();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.SelectMedicalRecord#getVariableMedicalRecordNext <em>Variable Medical Record Next</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Variable Medical Record Next</em>'.
   * @see ase.queryDsl.SelectMedicalRecord#getVariableMedicalRecordNext()
   * @see #getSelectMedicalRecord()
   * @generated
   */
  EAttribute getSelectMedicalRecord_VariableMedicalRecordNext();

  /**
   * Returns the meta object for the containment reference list '{@link ase.queryDsl.SelectMedicalRecord#getWhere <em>Where</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Where</em>'.
   * @see ase.queryDsl.SelectMedicalRecord#getWhere()
   * @see #getSelectMedicalRecord()
   * @generated
   */
  EReference getSelectMedicalRecord_Where();

  /**
   * Returns the meta object for class '{@link ase.queryDsl.SelectPatientMonitoring <em>Select Patient Monitoring</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select Patient Monitoring</em>'.
   * @see ase.queryDsl.SelectPatientMonitoring
   * @generated
   */
  EClass getSelectPatientMonitoring();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.SelectPatientMonitoring#getVariablePatientMonitoring <em>Variable Patient Monitoring</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Variable Patient Monitoring</em>'.
   * @see ase.queryDsl.SelectPatientMonitoring#getVariablePatientMonitoring()
   * @see #getSelectPatientMonitoring()
   * @generated
   */
  EAttribute getSelectPatientMonitoring_VariablePatientMonitoring();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.SelectPatientMonitoring#getVariablePatientMonitoringNext <em>Variable Patient Monitoring Next</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Variable Patient Monitoring Next</em>'.
   * @see ase.queryDsl.SelectPatientMonitoring#getVariablePatientMonitoringNext()
   * @see #getSelectPatientMonitoring()
   * @generated
   */
  EAttribute getSelectPatientMonitoring_VariablePatientMonitoringNext();

  /**
   * Returns the meta object for the containment reference list '{@link ase.queryDsl.SelectPatientMonitoring#getWhere <em>Where</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Where</em>'.
   * @see ase.queryDsl.SelectPatientMonitoring#getWhere()
   * @see #getSelectPatientMonitoring()
   * @generated
   */
  EReference getSelectPatientMonitoring_Where();

  /**
   * Returns the meta object for class '{@link ase.queryDsl.SelectPrescription <em>Select Prescription</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select Prescription</em>'.
   * @see ase.queryDsl.SelectPrescription
   * @generated
   */
  EClass getSelectPrescription();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.SelectPrescription#getVariablePrescription <em>Variable Prescription</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Variable Prescription</em>'.
   * @see ase.queryDsl.SelectPrescription#getVariablePrescription()
   * @see #getSelectPrescription()
   * @generated
   */
  EAttribute getSelectPrescription_VariablePrescription();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.SelectPrescription#getVariablePrescriptionNext <em>Variable Prescription Next</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Variable Prescription Next</em>'.
   * @see ase.queryDsl.SelectPrescription#getVariablePrescriptionNext()
   * @see #getSelectPrescription()
   * @generated
   */
  EAttribute getSelectPrescription_VariablePrescriptionNext();

  /**
   * Returns the meta object for the containment reference list '{@link ase.queryDsl.SelectPrescription#getWhere <em>Where</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Where</em>'.
   * @see ase.queryDsl.SelectPrescription#getWhere()
   * @see #getSelectPrescription()
   * @generated
   */
  EReference getSelectPrescription_Where();

  /**
   * Returns the meta object for class '{@link ase.queryDsl.Insert <em>Insert</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insert</em>'.
   * @see ase.queryDsl.Insert
   * @generated
   */
  EClass getInsert();

  /**
   * Returns the meta object for class '{@link ase.queryDsl.InsertMedicalRecord <em>Insert Medical Record</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insert Medical Record</em>'.
   * @see ase.queryDsl.InsertMedicalRecord
   * @generated
   */
  EClass getInsertMedicalRecord();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.InsertMedicalRecord#getRecordId <em>Record Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Record Id</em>'.
   * @see ase.queryDsl.InsertMedicalRecord#getRecordId()
   * @see #getInsertMedicalRecord()
   * @generated
   */
  EAttribute getInsertMedicalRecord_RecordId();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.InsertMedicalRecord#getPatientId <em>Patient Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Patient Id</em>'.
   * @see ase.queryDsl.InsertMedicalRecord#getPatientId()
   * @see #getInsertMedicalRecord()
   * @generated
   */
  EAttribute getInsertMedicalRecord_PatientId();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.InsertMedicalRecord#getDoctorId <em>Doctor Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Doctor Id</em>'.
   * @see ase.queryDsl.InsertMedicalRecord#getDoctorId()
   * @see #getInsertMedicalRecord()
   * @generated
   */
  EAttribute getInsertMedicalRecord_DoctorId();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.InsertMedicalRecord#getMedicalCondition <em>Medical Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Medical Condition</em>'.
   * @see ase.queryDsl.InsertMedicalRecord#getMedicalCondition()
   * @see #getInsertMedicalRecord()
   * @generated
   */
  EAttribute getInsertMedicalRecord_MedicalCondition();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.InsertMedicalRecord#getDate <em>Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Date</em>'.
   * @see ase.queryDsl.InsertMedicalRecord#getDate()
   * @see #getInsertMedicalRecord()
   * @generated
   */
  EAttribute getInsertMedicalRecord_Date();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.InsertMedicalRecord#getPrice <em>Price</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Price</em>'.
   * @see ase.queryDsl.InsertMedicalRecord#getPrice()
   * @see #getInsertMedicalRecord()
   * @generated
   */
  EAttribute getInsertMedicalRecord_Price();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.InsertMedicalRecord#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see ase.queryDsl.InsertMedicalRecord#getDescription()
   * @see #getInsertMedicalRecord()
   * @generated
   */
  EAttribute getInsertMedicalRecord_Description();

  /**
   * Returns the meta object for class '{@link ase.queryDsl.InsertPatientMonitoring <em>Insert Patient Monitoring</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insert Patient Monitoring</em>'.
   * @see ase.queryDsl.InsertPatientMonitoring
   * @generated
   */
  EClass getInsertPatientMonitoring();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.InsertPatientMonitoring#getMonitoringId <em>Monitoring Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Monitoring Id</em>'.
   * @see ase.queryDsl.InsertPatientMonitoring#getMonitoringId()
   * @see #getInsertPatientMonitoring()
   * @generated
   */
  EAttribute getInsertPatientMonitoring_MonitoringId();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.InsertPatientMonitoring#getPatientId <em>Patient Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Patient Id</em>'.
   * @see ase.queryDsl.InsertPatientMonitoring#getPatientId()
   * @see #getInsertPatientMonitoring()
   * @generated
   */
  EAttribute getInsertPatientMonitoring_PatientId();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.InsertPatientMonitoring#getCategory <em>Category</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Category</em>'.
   * @see ase.queryDsl.InsertPatientMonitoring#getCategory()
   * @see #getInsertPatientMonitoring()
   * @generated
   */
  EAttribute getInsertPatientMonitoring_Category();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.InsertPatientMonitoring#getDate <em>Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Date</em>'.
   * @see ase.queryDsl.InsertPatientMonitoring#getDate()
   * @see #getInsertPatientMonitoring()
   * @generated
   */
  EAttribute getInsertPatientMonitoring_Date();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.InsertPatientMonitoring#getRiskPerception <em>Risk Perception</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Risk Perception</em>'.
   * @see ase.queryDsl.InsertPatientMonitoring#getRiskPerception()
   * @see #getInsertPatientMonitoring()
   * @generated
   */
  EAttribute getInsertPatientMonitoring_RiskPerception();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.InsertPatientMonitoring#getTreadted <em>Treadted</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Treadted</em>'.
   * @see ase.queryDsl.InsertPatientMonitoring#getTreadted()
   * @see #getInsertPatientMonitoring()
   * @generated
   */
  EAttribute getInsertPatientMonitoring_Treadted();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.InsertPatientMonitoring#getDeviceId <em>Device Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Device Id</em>'.
   * @see ase.queryDsl.InsertPatientMonitoring#getDeviceId()
   * @see #getInsertPatientMonitoring()
   * @generated
   */
  EAttribute getInsertPatientMonitoring_DeviceId();

  /**
   * Returns the meta object for class '{@link ase.queryDsl.InsertPrescription <em>Insert Prescription</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insert Prescription</em>'.
   * @see ase.queryDsl.InsertPrescription
   * @generated
   */
  EClass getInsertPrescription();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.InsertPrescription#getPrescriptionId <em>Prescription Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prescription Id</em>'.
   * @see ase.queryDsl.InsertPrescription#getPrescriptionId()
   * @see #getInsertPrescription()
   * @generated
   */
  EAttribute getInsertPrescription_PrescriptionId();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.InsertPrescription#getRecordId <em>Record Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Record Id</em>'.
   * @see ase.queryDsl.InsertPrescription#getRecordId()
   * @see #getInsertPrescription()
   * @generated
   */
  EAttribute getInsertPrescription_RecordId();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.InsertPrescription#getMedicationName <em>Medication Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Medication Name</em>'.
   * @see ase.queryDsl.InsertPrescription#getMedicationName()
   * @see #getInsertPrescription()
   * @generated
   */
  EAttribute getInsertPrescription_MedicationName();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.InsertPrescription#getStart <em>Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start</em>'.
   * @see ase.queryDsl.InsertPrescription#getStart()
   * @see #getInsertPrescription()
   * @generated
   */
  EAttribute getInsertPrescription_Start();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.InsertPrescription#getEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End</em>'.
   * @see ase.queryDsl.InsertPrescription#getEnd()
   * @see #getInsertPrescription()
   * @generated
   */
  EAttribute getInsertPrescription_End();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.InsertPrescription#getOrdered <em>Ordered</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ordered</em>'.
   * @see ase.queryDsl.InsertPrescription#getOrdered()
   * @see #getInsertPrescription()
   * @generated
   */
  EAttribute getInsertPrescription_Ordered();

  /**
   * Returns the meta object for the attribute '{@link ase.queryDsl.InsertPrescription#getPrice <em>Price</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Price</em>'.
   * @see ase.queryDsl.InsertPrescription#getPrice()
   * @see #getInsertPrescription()
   * @generated
   */
  EAttribute getInsertPrescription_Price();

  /**
   * Returns the meta object for class '{@link ase.queryDsl.Drop <em>Drop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Drop</em>'.
   * @see ase.queryDsl.Drop
   * @generated
   */
  EClass getDrop();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.Drop#getTable_name <em>Table name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Table name</em>'.
   * @see ase.queryDsl.Drop#getTable_name()
   * @see #getDrop()
   * @generated
   */
  EAttribute getDrop_Table_name();

  /**
   * Returns the meta object for class '{@link ase.queryDsl.Delete <em>Delete</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Delete</em>'.
   * @see ase.queryDsl.Delete
   * @generated
   */
  EClass getDelete();

  /**
   * Returns the meta object for class '{@link ase.queryDsl.DeleteMedicalRecord <em>Delete Medical Record</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Delete Medical Record</em>'.
   * @see ase.queryDsl.DeleteMedicalRecord
   * @generated
   */
  EClass getDeleteMedicalRecord();

  /**
   * Returns the meta object for the containment reference list '{@link ase.queryDsl.DeleteMedicalRecord#getWhereMedicalRecord <em>Where Medical Record</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Where Medical Record</em>'.
   * @see ase.queryDsl.DeleteMedicalRecord#getWhereMedicalRecord()
   * @see #getDeleteMedicalRecord()
   * @generated
   */
  EReference getDeleteMedicalRecord_WhereMedicalRecord();

  /**
   * Returns the meta object for class '{@link ase.queryDsl.DeletePatientMonitoring <em>Delete Patient Monitoring</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Delete Patient Monitoring</em>'.
   * @see ase.queryDsl.DeletePatientMonitoring
   * @generated
   */
  EClass getDeletePatientMonitoring();

  /**
   * Returns the meta object for the containment reference list '{@link ase.queryDsl.DeletePatientMonitoring#getWherepatientMonitoring <em>Wherepatient Monitoring</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Wherepatient Monitoring</em>'.
   * @see ase.queryDsl.DeletePatientMonitoring#getWherepatientMonitoring()
   * @see #getDeletePatientMonitoring()
   * @generated
   */
  EReference getDeletePatientMonitoring_WherepatientMonitoring();

  /**
   * Returns the meta object for class '{@link ase.queryDsl.DeletePrescription <em>Delete Prescription</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Delete Prescription</em>'.
   * @see ase.queryDsl.DeletePrescription
   * @generated
   */
  EClass getDeletePrescription();

  /**
   * Returns the meta object for the containment reference list '{@link ase.queryDsl.DeletePrescription#getWhereprescription <em>Whereprescription</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Whereprescription</em>'.
   * @see ase.queryDsl.DeletePrescription#getWhereprescription()
   * @see #getDeletePrescription()
   * @generated
   */
  EReference getDeletePrescription_Whereprescription();

  /**
   * Returns the meta object for class '{@link ase.queryDsl.WhereMedicalRecord <em>Where Medical Record</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Where Medical Record</em>'.
   * @see ase.queryDsl.WhereMedicalRecord
   * @generated
   */
  EClass getWhereMedicalRecord();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.WhereMedicalRecord#getRecordId <em>Record Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Record Id</em>'.
   * @see ase.queryDsl.WhereMedicalRecord#getRecordId()
   * @see #getWhereMedicalRecord()
   * @generated
   */
  EAttribute getWhereMedicalRecord_RecordId();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.WhereMedicalRecord#getPatientId <em>Patient Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Patient Id</em>'.
   * @see ase.queryDsl.WhereMedicalRecord#getPatientId()
   * @see #getWhereMedicalRecord()
   * @generated
   */
  EAttribute getWhereMedicalRecord_PatientId();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.WhereMedicalRecord#getDoctorId <em>Doctor Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Doctor Id</em>'.
   * @see ase.queryDsl.WhereMedicalRecord#getDoctorId()
   * @see #getWhereMedicalRecord()
   * @generated
   */
  EAttribute getWhereMedicalRecord_DoctorId();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.WhereMedicalRecord#getMedicalCondition <em>Medical Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Medical Condition</em>'.
   * @see ase.queryDsl.WhereMedicalRecord#getMedicalCondition()
   * @see #getWhereMedicalRecord()
   * @generated
   */
  EAttribute getWhereMedicalRecord_MedicalCondition();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.WhereMedicalRecord#getDate <em>Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Date</em>'.
   * @see ase.queryDsl.WhereMedicalRecord#getDate()
   * @see #getWhereMedicalRecord()
   * @generated
   */
  EAttribute getWhereMedicalRecord_Date();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.WhereMedicalRecord#getPrice <em>Price</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Price</em>'.
   * @see ase.queryDsl.WhereMedicalRecord#getPrice()
   * @see #getWhereMedicalRecord()
   * @generated
   */
  EAttribute getWhereMedicalRecord_Price();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.WhereMedicalRecord#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Description</em>'.
   * @see ase.queryDsl.WhereMedicalRecord#getDescription()
   * @see #getWhereMedicalRecord()
   * @generated
   */
  EAttribute getWhereMedicalRecord_Description();

  /**
   * Returns the meta object for class '{@link ase.queryDsl.WherePatientMonitoring <em>Where Patient Monitoring</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Where Patient Monitoring</em>'.
   * @see ase.queryDsl.WherePatientMonitoring
   * @generated
   */
  EClass getWherePatientMonitoring();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.WherePatientMonitoring#getMonitoringId <em>Monitoring Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Monitoring Id</em>'.
   * @see ase.queryDsl.WherePatientMonitoring#getMonitoringId()
   * @see #getWherePatientMonitoring()
   * @generated
   */
  EAttribute getWherePatientMonitoring_MonitoringId();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.WherePatientMonitoring#getPatientId <em>Patient Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Patient Id</em>'.
   * @see ase.queryDsl.WherePatientMonitoring#getPatientId()
   * @see #getWherePatientMonitoring()
   * @generated
   */
  EAttribute getWherePatientMonitoring_PatientId();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.WherePatientMonitoring#getCategory <em>Category</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Category</em>'.
   * @see ase.queryDsl.WherePatientMonitoring#getCategory()
   * @see #getWherePatientMonitoring()
   * @generated
   */
  EAttribute getWherePatientMonitoring_Category();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.WherePatientMonitoring#getDate <em>Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Date</em>'.
   * @see ase.queryDsl.WherePatientMonitoring#getDate()
   * @see #getWherePatientMonitoring()
   * @generated
   */
  EAttribute getWherePatientMonitoring_Date();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.WherePatientMonitoring#getRiskperception <em>Riskperception</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Riskperception</em>'.
   * @see ase.queryDsl.WherePatientMonitoring#getRiskperception()
   * @see #getWherePatientMonitoring()
   * @generated
   */
  EAttribute getWherePatientMonitoring_Riskperception();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.WherePatientMonitoring#getTreated <em>Treated</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Treated</em>'.
   * @see ase.queryDsl.WherePatientMonitoring#getTreated()
   * @see #getWherePatientMonitoring()
   * @generated
   */
  EAttribute getWherePatientMonitoring_Treated();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.WherePatientMonitoring#getDeviceId <em>Device Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Device Id</em>'.
   * @see ase.queryDsl.WherePatientMonitoring#getDeviceId()
   * @see #getWherePatientMonitoring()
   * @generated
   */
  EAttribute getWherePatientMonitoring_DeviceId();

  /**
   * Returns the meta object for class '{@link ase.queryDsl.WherePrescription <em>Where Prescription</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Where Prescription</em>'.
   * @see ase.queryDsl.WherePrescription
   * @generated
   */
  EClass getWherePrescription();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.WherePrescription#getPrescriptionId <em>Prescription Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Prescription Id</em>'.
   * @see ase.queryDsl.WherePrescription#getPrescriptionId()
   * @see #getWherePrescription()
   * @generated
   */
  EAttribute getWherePrescription_PrescriptionId();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.WherePrescription#getRecordId <em>Record Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Record Id</em>'.
   * @see ase.queryDsl.WherePrescription#getRecordId()
   * @see #getWherePrescription()
   * @generated
   */
  EAttribute getWherePrescription_RecordId();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.WherePrescription#getMedicationName <em>Medication Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Medication Name</em>'.
   * @see ase.queryDsl.WherePrescription#getMedicationName()
   * @see #getWherePrescription()
   * @generated
   */
  EAttribute getWherePrescription_MedicationName();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.WherePrescription#getStart <em>Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Start</em>'.
   * @see ase.queryDsl.WherePrescription#getStart()
   * @see #getWherePrescription()
   * @generated
   */
  EAttribute getWherePrescription_Start();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.WherePrescription#getEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>End</em>'.
   * @see ase.queryDsl.WherePrescription#getEnd()
   * @see #getWherePrescription()
   * @generated
   */
  EAttribute getWherePrescription_End();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.WherePrescription#getOrdered <em>Ordered</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Ordered</em>'.
   * @see ase.queryDsl.WherePrescription#getOrdered()
   * @see #getWherePrescription()
   * @generated
   */
  EAttribute getWherePrescription_Ordered();

  /**
   * Returns the meta object for the attribute list '{@link ase.queryDsl.WherePrescription#getPrice <em>Price</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Price</em>'.
   * @see ase.queryDsl.WherePrescription#getPrice()
   * @see #getWherePrescription()
   * @generated
   */
  EAttribute getWherePrescription_Price();

  /**
   * Returns the meta object for enum '{@link ase.queryDsl.TableName <em>Table Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Table Name</em>'.
   * @see ase.queryDsl.TableName
   * @generated
   */
  EEnum getTableName();

  /**
   * Returns the meta object for enum '{@link ase.queryDsl.VariableMedicalRecord <em>Variable Medical Record</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Variable Medical Record</em>'.
   * @see ase.queryDsl.VariableMedicalRecord
   * @generated
   */
  EEnum getVariableMedicalRecord();

  /**
   * Returns the meta object for enum '{@link ase.queryDsl.VariablePatientMonitoring <em>Variable Patient Monitoring</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Variable Patient Monitoring</em>'.
   * @see ase.queryDsl.VariablePatientMonitoring
   * @generated
   */
  EEnum getVariablePatientMonitoring();

  /**
   * Returns the meta object for enum '{@link ase.queryDsl.VariablePrescription <em>Variable Prescription</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Variable Prescription</em>'.
   * @see ase.queryDsl.VariablePrescription
   * @generated
   */
  EEnum getVariablePrescription();

  /**
   * Returns the meta object for enum '{@link ase.queryDsl.MedicalCondition <em>Medical Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Medical Condition</em>'.
   * @see ase.queryDsl.MedicalCondition
   * @generated
   */
  EEnum getMedicalCondition();

  /**
   * Returns the meta object for enum '{@link ase.queryDsl.RiskPerception <em>Risk Perception</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Risk Perception</em>'.
   * @see ase.queryDsl.RiskPerception
   * @generated
   */
  EEnum getRiskPerception();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  QueryDslFactory getQueryDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link ase.queryDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.impl.ModelImpl
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Query Type</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__QUERY_TYPE = eINSTANCE.getModel_QueryType();

    /**
     * The meta object literal for the '{@link ase.queryDsl.impl.QueryTypeImpl <em>Query Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.impl.QueryTypeImpl
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getQueryType()
     * @generated
     */
    EClass QUERY_TYPE = eINSTANCE.getQueryType();

    /**
     * The meta object literal for the '{@link ase.queryDsl.impl.SelectImpl <em>Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.impl.SelectImpl
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getSelect()
     * @generated
     */
    EClass SELECT = eINSTANCE.getSelect();

    /**
     * The meta object literal for the '{@link ase.queryDsl.impl.SelectMedicalRecordImpl <em>Select Medical Record</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.impl.SelectMedicalRecordImpl
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getSelectMedicalRecord()
     * @generated
     */
    EClass SELECT_MEDICAL_RECORD = eINSTANCE.getSelectMedicalRecord();

    /**
     * The meta object literal for the '<em><b>Variable Medical Record</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT_MEDICAL_RECORD__VARIABLE_MEDICAL_RECORD = eINSTANCE.getSelectMedicalRecord_VariableMedicalRecord();

    /**
     * The meta object literal for the '<em><b>Variable Medical Record Next</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT_MEDICAL_RECORD__VARIABLE_MEDICAL_RECORD_NEXT = eINSTANCE.getSelectMedicalRecord_VariableMedicalRecordNext();

    /**
     * The meta object literal for the '<em><b>Where</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT_MEDICAL_RECORD__WHERE = eINSTANCE.getSelectMedicalRecord_Where();

    /**
     * The meta object literal for the '{@link ase.queryDsl.impl.SelectPatientMonitoringImpl <em>Select Patient Monitoring</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.impl.SelectPatientMonitoringImpl
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getSelectPatientMonitoring()
     * @generated
     */
    EClass SELECT_PATIENT_MONITORING = eINSTANCE.getSelectPatientMonitoring();

    /**
     * The meta object literal for the '<em><b>Variable Patient Monitoring</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT_PATIENT_MONITORING__VARIABLE_PATIENT_MONITORING = eINSTANCE.getSelectPatientMonitoring_VariablePatientMonitoring();

    /**
     * The meta object literal for the '<em><b>Variable Patient Monitoring Next</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT_PATIENT_MONITORING__VARIABLE_PATIENT_MONITORING_NEXT = eINSTANCE.getSelectPatientMonitoring_VariablePatientMonitoringNext();

    /**
     * The meta object literal for the '<em><b>Where</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT_PATIENT_MONITORING__WHERE = eINSTANCE.getSelectPatientMonitoring_Where();

    /**
     * The meta object literal for the '{@link ase.queryDsl.impl.SelectPrescriptionImpl <em>Select Prescription</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.impl.SelectPrescriptionImpl
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getSelectPrescription()
     * @generated
     */
    EClass SELECT_PRESCRIPTION = eINSTANCE.getSelectPrescription();

    /**
     * The meta object literal for the '<em><b>Variable Prescription</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT_PRESCRIPTION__VARIABLE_PRESCRIPTION = eINSTANCE.getSelectPrescription_VariablePrescription();

    /**
     * The meta object literal for the '<em><b>Variable Prescription Next</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT_PRESCRIPTION__VARIABLE_PRESCRIPTION_NEXT = eINSTANCE.getSelectPrescription_VariablePrescriptionNext();

    /**
     * The meta object literal for the '<em><b>Where</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT_PRESCRIPTION__WHERE = eINSTANCE.getSelectPrescription_Where();

    /**
     * The meta object literal for the '{@link ase.queryDsl.impl.InsertImpl <em>Insert</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.impl.InsertImpl
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getInsert()
     * @generated
     */
    EClass INSERT = eINSTANCE.getInsert();

    /**
     * The meta object literal for the '{@link ase.queryDsl.impl.InsertMedicalRecordImpl <em>Insert Medical Record</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.impl.InsertMedicalRecordImpl
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getInsertMedicalRecord()
     * @generated
     */
    EClass INSERT_MEDICAL_RECORD = eINSTANCE.getInsertMedicalRecord();

    /**
     * The meta object literal for the '<em><b>Record Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_MEDICAL_RECORD__RECORD_ID = eINSTANCE.getInsertMedicalRecord_RecordId();

    /**
     * The meta object literal for the '<em><b>Patient Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_MEDICAL_RECORD__PATIENT_ID = eINSTANCE.getInsertMedicalRecord_PatientId();

    /**
     * The meta object literal for the '<em><b>Doctor Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_MEDICAL_RECORD__DOCTOR_ID = eINSTANCE.getInsertMedicalRecord_DoctorId();

    /**
     * The meta object literal for the '<em><b>Medical Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_MEDICAL_RECORD__MEDICAL_CONDITION = eINSTANCE.getInsertMedicalRecord_MedicalCondition();

    /**
     * The meta object literal for the '<em><b>Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_MEDICAL_RECORD__DATE = eINSTANCE.getInsertMedicalRecord_Date();

    /**
     * The meta object literal for the '<em><b>Price</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_MEDICAL_RECORD__PRICE = eINSTANCE.getInsertMedicalRecord_Price();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_MEDICAL_RECORD__DESCRIPTION = eINSTANCE.getInsertMedicalRecord_Description();

    /**
     * The meta object literal for the '{@link ase.queryDsl.impl.InsertPatientMonitoringImpl <em>Insert Patient Monitoring</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.impl.InsertPatientMonitoringImpl
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getInsertPatientMonitoring()
     * @generated
     */
    EClass INSERT_PATIENT_MONITORING = eINSTANCE.getInsertPatientMonitoring();

    /**
     * The meta object literal for the '<em><b>Monitoring Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_PATIENT_MONITORING__MONITORING_ID = eINSTANCE.getInsertPatientMonitoring_MonitoringId();

    /**
     * The meta object literal for the '<em><b>Patient Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_PATIENT_MONITORING__PATIENT_ID = eINSTANCE.getInsertPatientMonitoring_PatientId();

    /**
     * The meta object literal for the '<em><b>Category</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_PATIENT_MONITORING__CATEGORY = eINSTANCE.getInsertPatientMonitoring_Category();

    /**
     * The meta object literal for the '<em><b>Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_PATIENT_MONITORING__DATE = eINSTANCE.getInsertPatientMonitoring_Date();

    /**
     * The meta object literal for the '<em><b>Risk Perception</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_PATIENT_MONITORING__RISK_PERCEPTION = eINSTANCE.getInsertPatientMonitoring_RiskPerception();

    /**
     * The meta object literal for the '<em><b>Treadted</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_PATIENT_MONITORING__TREADTED = eINSTANCE.getInsertPatientMonitoring_Treadted();

    /**
     * The meta object literal for the '<em><b>Device Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_PATIENT_MONITORING__DEVICE_ID = eINSTANCE.getInsertPatientMonitoring_DeviceId();

    /**
     * The meta object literal for the '{@link ase.queryDsl.impl.InsertPrescriptionImpl <em>Insert Prescription</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.impl.InsertPrescriptionImpl
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getInsertPrescription()
     * @generated
     */
    EClass INSERT_PRESCRIPTION = eINSTANCE.getInsertPrescription();

    /**
     * The meta object literal for the '<em><b>Prescription Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_PRESCRIPTION__PRESCRIPTION_ID = eINSTANCE.getInsertPrescription_PrescriptionId();

    /**
     * The meta object literal for the '<em><b>Record Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_PRESCRIPTION__RECORD_ID = eINSTANCE.getInsertPrescription_RecordId();

    /**
     * The meta object literal for the '<em><b>Medication Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_PRESCRIPTION__MEDICATION_NAME = eINSTANCE.getInsertPrescription_MedicationName();

    /**
     * The meta object literal for the '<em><b>Start</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_PRESCRIPTION__START = eINSTANCE.getInsertPrescription_Start();

    /**
     * The meta object literal for the '<em><b>End</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_PRESCRIPTION__END = eINSTANCE.getInsertPrescription_End();

    /**
     * The meta object literal for the '<em><b>Ordered</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_PRESCRIPTION__ORDERED = eINSTANCE.getInsertPrescription_Ordered();

    /**
     * The meta object literal for the '<em><b>Price</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_PRESCRIPTION__PRICE = eINSTANCE.getInsertPrescription_Price();

    /**
     * The meta object literal for the '{@link ase.queryDsl.impl.DropImpl <em>Drop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.impl.DropImpl
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getDrop()
     * @generated
     */
    EClass DROP = eINSTANCE.getDrop();

    /**
     * The meta object literal for the '<em><b>Table name</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DROP__TABLE_NAME = eINSTANCE.getDrop_Table_name();

    /**
     * The meta object literal for the '{@link ase.queryDsl.impl.DeleteImpl <em>Delete</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.impl.DeleteImpl
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getDelete()
     * @generated
     */
    EClass DELETE = eINSTANCE.getDelete();

    /**
     * The meta object literal for the '{@link ase.queryDsl.impl.DeleteMedicalRecordImpl <em>Delete Medical Record</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.impl.DeleteMedicalRecordImpl
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getDeleteMedicalRecord()
     * @generated
     */
    EClass DELETE_MEDICAL_RECORD = eINSTANCE.getDeleteMedicalRecord();

    /**
     * The meta object literal for the '<em><b>Where Medical Record</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DELETE_MEDICAL_RECORD__WHERE_MEDICAL_RECORD = eINSTANCE.getDeleteMedicalRecord_WhereMedicalRecord();

    /**
     * The meta object literal for the '{@link ase.queryDsl.impl.DeletePatientMonitoringImpl <em>Delete Patient Monitoring</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.impl.DeletePatientMonitoringImpl
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getDeletePatientMonitoring()
     * @generated
     */
    EClass DELETE_PATIENT_MONITORING = eINSTANCE.getDeletePatientMonitoring();

    /**
     * The meta object literal for the '<em><b>Wherepatient Monitoring</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DELETE_PATIENT_MONITORING__WHEREPATIENT_MONITORING = eINSTANCE.getDeletePatientMonitoring_WherepatientMonitoring();

    /**
     * The meta object literal for the '{@link ase.queryDsl.impl.DeletePrescriptionImpl <em>Delete Prescription</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.impl.DeletePrescriptionImpl
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getDeletePrescription()
     * @generated
     */
    EClass DELETE_PRESCRIPTION = eINSTANCE.getDeletePrescription();

    /**
     * The meta object literal for the '<em><b>Whereprescription</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DELETE_PRESCRIPTION__WHEREPRESCRIPTION = eINSTANCE.getDeletePrescription_Whereprescription();

    /**
     * The meta object literal for the '{@link ase.queryDsl.impl.WhereMedicalRecordImpl <em>Where Medical Record</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.impl.WhereMedicalRecordImpl
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getWhereMedicalRecord()
     * @generated
     */
    EClass WHERE_MEDICAL_RECORD = eINSTANCE.getWhereMedicalRecord();

    /**
     * The meta object literal for the '<em><b>Record Id</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE_MEDICAL_RECORD__RECORD_ID = eINSTANCE.getWhereMedicalRecord_RecordId();

    /**
     * The meta object literal for the '<em><b>Patient Id</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE_MEDICAL_RECORD__PATIENT_ID = eINSTANCE.getWhereMedicalRecord_PatientId();

    /**
     * The meta object literal for the '<em><b>Doctor Id</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE_MEDICAL_RECORD__DOCTOR_ID = eINSTANCE.getWhereMedicalRecord_DoctorId();

    /**
     * The meta object literal for the '<em><b>Medical Condition</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE_MEDICAL_RECORD__MEDICAL_CONDITION = eINSTANCE.getWhereMedicalRecord_MedicalCondition();

    /**
     * The meta object literal for the '<em><b>Date</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE_MEDICAL_RECORD__DATE = eINSTANCE.getWhereMedicalRecord_Date();

    /**
     * The meta object literal for the '<em><b>Price</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE_MEDICAL_RECORD__PRICE = eINSTANCE.getWhereMedicalRecord_Price();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE_MEDICAL_RECORD__DESCRIPTION = eINSTANCE.getWhereMedicalRecord_Description();

    /**
     * The meta object literal for the '{@link ase.queryDsl.impl.WherePatientMonitoringImpl <em>Where Patient Monitoring</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.impl.WherePatientMonitoringImpl
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getWherePatientMonitoring()
     * @generated
     */
    EClass WHERE_PATIENT_MONITORING = eINSTANCE.getWherePatientMonitoring();

    /**
     * The meta object literal for the '<em><b>Monitoring Id</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE_PATIENT_MONITORING__MONITORING_ID = eINSTANCE.getWherePatientMonitoring_MonitoringId();

    /**
     * The meta object literal for the '<em><b>Patient Id</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE_PATIENT_MONITORING__PATIENT_ID = eINSTANCE.getWherePatientMonitoring_PatientId();

    /**
     * The meta object literal for the '<em><b>Category</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE_PATIENT_MONITORING__CATEGORY = eINSTANCE.getWherePatientMonitoring_Category();

    /**
     * The meta object literal for the '<em><b>Date</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE_PATIENT_MONITORING__DATE = eINSTANCE.getWherePatientMonitoring_Date();

    /**
     * The meta object literal for the '<em><b>Riskperception</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE_PATIENT_MONITORING__RISKPERCEPTION = eINSTANCE.getWherePatientMonitoring_Riskperception();

    /**
     * The meta object literal for the '<em><b>Treated</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE_PATIENT_MONITORING__TREATED = eINSTANCE.getWherePatientMonitoring_Treated();

    /**
     * The meta object literal for the '<em><b>Device Id</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE_PATIENT_MONITORING__DEVICE_ID = eINSTANCE.getWherePatientMonitoring_DeviceId();

    /**
     * The meta object literal for the '{@link ase.queryDsl.impl.WherePrescriptionImpl <em>Where Prescription</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.impl.WherePrescriptionImpl
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getWherePrescription()
     * @generated
     */
    EClass WHERE_PRESCRIPTION = eINSTANCE.getWherePrescription();

    /**
     * The meta object literal for the '<em><b>Prescription Id</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE_PRESCRIPTION__PRESCRIPTION_ID = eINSTANCE.getWherePrescription_PrescriptionId();

    /**
     * The meta object literal for the '<em><b>Record Id</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE_PRESCRIPTION__RECORD_ID = eINSTANCE.getWherePrescription_RecordId();

    /**
     * The meta object literal for the '<em><b>Medication Name</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE_PRESCRIPTION__MEDICATION_NAME = eINSTANCE.getWherePrescription_MedicationName();

    /**
     * The meta object literal for the '<em><b>Start</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE_PRESCRIPTION__START = eINSTANCE.getWherePrescription_Start();

    /**
     * The meta object literal for the '<em><b>End</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE_PRESCRIPTION__END = eINSTANCE.getWherePrescription_End();

    /**
     * The meta object literal for the '<em><b>Ordered</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE_PRESCRIPTION__ORDERED = eINSTANCE.getWherePrescription_Ordered();

    /**
     * The meta object literal for the '<em><b>Price</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE_PRESCRIPTION__PRICE = eINSTANCE.getWherePrescription_Price();

    /**
     * The meta object literal for the '{@link ase.queryDsl.TableName <em>Table Name</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.TableName
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getTableName()
     * @generated
     */
    EEnum TABLE_NAME = eINSTANCE.getTableName();

    /**
     * The meta object literal for the '{@link ase.queryDsl.VariableMedicalRecord <em>Variable Medical Record</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.VariableMedicalRecord
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getVariableMedicalRecord()
     * @generated
     */
    EEnum VARIABLE_MEDICAL_RECORD = eINSTANCE.getVariableMedicalRecord();

    /**
     * The meta object literal for the '{@link ase.queryDsl.VariablePatientMonitoring <em>Variable Patient Monitoring</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.VariablePatientMonitoring
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getVariablePatientMonitoring()
     * @generated
     */
    EEnum VARIABLE_PATIENT_MONITORING = eINSTANCE.getVariablePatientMonitoring();

    /**
     * The meta object literal for the '{@link ase.queryDsl.VariablePrescription <em>Variable Prescription</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.VariablePrescription
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getVariablePrescription()
     * @generated
     */
    EEnum VARIABLE_PRESCRIPTION = eINSTANCE.getVariablePrescription();

    /**
     * The meta object literal for the '{@link ase.queryDsl.MedicalCondition <em>Medical Condition</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.MedicalCondition
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getMedicalCondition()
     * @generated
     */
    EEnum MEDICAL_CONDITION = eINSTANCE.getMedicalCondition();

    /**
     * The meta object literal for the '{@link ase.queryDsl.RiskPerception <em>Risk Perception</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ase.queryDsl.RiskPerception
     * @see ase.queryDsl.impl.QueryDslPackageImpl#getRiskPerception()
     * @generated
     */
    EEnum RISK_PERCEPTION = eINSTANCE.getRiskPerception();

  }

} //QueryDslPackage
