/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Query Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ase.queryDsl.QueryDslPackage#getQueryType()
 * @model
 * @generated
 */
public interface QueryType extends EObject
{
} // QueryType
