/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Select</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ase.queryDsl.QueryDslPackage#getSelect()
 * @model
 * @generated
 */
public interface Select extends QueryType
{
} // Select
