/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Select Patient Monitoring</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ase.queryDsl.SelectPatientMonitoring#getVariablePatientMonitoring <em>Variable Patient Monitoring</em>}</li>
 *   <li>{@link ase.queryDsl.SelectPatientMonitoring#getVariablePatientMonitoringNext <em>Variable Patient Monitoring Next</em>}</li>
 *   <li>{@link ase.queryDsl.SelectPatientMonitoring#getWhere <em>Where</em>}</li>
 * </ul>
 *
 * @see ase.queryDsl.QueryDslPackage#getSelectPatientMonitoring()
 * @model
 * @generated
 */
public interface SelectPatientMonitoring extends Select
{
  /**
   * Returns the value of the '<em><b>Variable Patient Monitoring</b></em>' attribute.
   * The literals are from the enumeration {@link ase.queryDsl.VariablePatientMonitoring}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variable Patient Monitoring</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable Patient Monitoring</em>' attribute.
   * @see ase.queryDsl.VariablePatientMonitoring
   * @see #setVariablePatientMonitoring(VariablePatientMonitoring)
   * @see ase.queryDsl.QueryDslPackage#getSelectPatientMonitoring_VariablePatientMonitoring()
   * @model
   * @generated
   */
  VariablePatientMonitoring getVariablePatientMonitoring();

  /**
   * Sets the value of the '{@link ase.queryDsl.SelectPatientMonitoring#getVariablePatientMonitoring <em>Variable Patient Monitoring</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable Patient Monitoring</em>' attribute.
   * @see ase.queryDsl.VariablePatientMonitoring
   * @see #getVariablePatientMonitoring()
   * @generated
   */
  void setVariablePatientMonitoring(VariablePatientMonitoring value);

  /**
   * Returns the value of the '<em><b>Variable Patient Monitoring Next</b></em>' attribute list.
   * The list contents are of type {@link ase.queryDsl.VariablePatientMonitoring}.
   * The literals are from the enumeration {@link ase.queryDsl.VariablePatientMonitoring}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variable Patient Monitoring Next</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable Patient Monitoring Next</em>' attribute list.
   * @see ase.queryDsl.VariablePatientMonitoring
   * @see ase.queryDsl.QueryDslPackage#getSelectPatientMonitoring_VariablePatientMonitoringNext()
   * @model unique="false"
   * @generated
   */
  EList<VariablePatientMonitoring> getVariablePatientMonitoringNext();

  /**
   * Returns the value of the '<em><b>Where</b></em>' containment reference list.
   * The list contents are of type {@link ase.queryDsl.WherePatientMonitoring}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Where</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Where</em>' containment reference list.
   * @see ase.queryDsl.QueryDslPackage#getSelectPatientMonitoring_Where()
   * @model containment="true"
   * @generated
   */
  EList<WherePatientMonitoring> getWhere();

} // SelectPatientMonitoring
