/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Select Medical Record</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ase.queryDsl.SelectMedicalRecord#getVariableMedicalRecord <em>Variable Medical Record</em>}</li>
 *   <li>{@link ase.queryDsl.SelectMedicalRecord#getVariableMedicalRecordNext <em>Variable Medical Record Next</em>}</li>
 *   <li>{@link ase.queryDsl.SelectMedicalRecord#getWhere <em>Where</em>}</li>
 * </ul>
 *
 * @see ase.queryDsl.QueryDslPackage#getSelectMedicalRecord()
 * @model
 * @generated
 */
public interface SelectMedicalRecord extends Select
{
  /**
   * Returns the value of the '<em><b>Variable Medical Record</b></em>' attribute list.
   * The list contents are of type {@link ase.queryDsl.VariableMedicalRecord}.
   * The literals are from the enumeration {@link ase.queryDsl.VariableMedicalRecord}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variable Medical Record</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable Medical Record</em>' attribute list.
   * @see ase.queryDsl.VariableMedicalRecord
   * @see ase.queryDsl.QueryDslPackage#getSelectMedicalRecord_VariableMedicalRecord()
   * @model unique="false"
   * @generated
   */
  EList<VariableMedicalRecord> getVariableMedicalRecord();

  /**
   * Returns the value of the '<em><b>Variable Medical Record Next</b></em>' attribute list.
   * The list contents are of type {@link ase.queryDsl.VariableMedicalRecord}.
   * The literals are from the enumeration {@link ase.queryDsl.VariableMedicalRecord}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variable Medical Record Next</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable Medical Record Next</em>' attribute list.
   * @see ase.queryDsl.VariableMedicalRecord
   * @see ase.queryDsl.QueryDslPackage#getSelectMedicalRecord_VariableMedicalRecordNext()
   * @model unique="false"
   * @generated
   */
  EList<VariableMedicalRecord> getVariableMedicalRecordNext();

  /**
   * Returns the value of the '<em><b>Where</b></em>' containment reference list.
   * The list contents are of type {@link ase.queryDsl.WhereMedicalRecord}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Where</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Where</em>' containment reference list.
   * @see ase.queryDsl.QueryDslPackage#getSelectMedicalRecord_Where()
   * @model containment="true"
   * @generated
   */
  EList<WhereMedicalRecord> getWhere();

} // SelectMedicalRecord
