/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Table Name</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see ase.queryDsl.QueryDslPackage#getTableName()
 * @model
 * @generated
 */
public enum TableName implements Enumerator
{
  /**
   * The '<em><b>Medical Record</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MEDICAL_RECORD_VALUE
   * @generated
   * @ordered
   */
  MEDICAL_RECORD(0, "MedicalRecord", "MedicalRecord"),

  /**
   * The '<em><b>Patient Monitoring</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PATIENT_MONITORING_VALUE
   * @generated
   * @ordered
   */
  PATIENT_MONITORING(1, "PatientMonitoring", "PatientMonitoring"),

  /**
   * The '<em><b>Prescription</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PRESCRIPTION_VALUE
   * @generated
   * @ordered
   */
  PRESCRIPTION(2, "Prescription", "Prescription");

  /**
   * The '<em><b>Medical Record</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Medical Record</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MEDICAL_RECORD
   * @model name="MedicalRecord"
   * @generated
   * @ordered
   */
  public static final int MEDICAL_RECORD_VALUE = 0;

  /**
   * The '<em><b>Patient Monitoring</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Patient Monitoring</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #PATIENT_MONITORING
   * @model name="PatientMonitoring"
   * @generated
   * @ordered
   */
  public static final int PATIENT_MONITORING_VALUE = 1;

  /**
   * The '<em><b>Prescription</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Prescription</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #PRESCRIPTION
   * @model name="Prescription"
   * @generated
   * @ordered
   */
  public static final int PRESCRIPTION_VALUE = 2;

  /**
   * An array of all the '<em><b>Table Name</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final TableName[] VALUES_ARRAY =
    new TableName[]
    {
      MEDICAL_RECORD,
      PATIENT_MONITORING,
      PRESCRIPTION,
    };

  /**
   * A public read-only list of all the '<em><b>Table Name</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<TableName> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Table Name</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static TableName get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      TableName result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Table Name</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static TableName getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      TableName result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Table Name</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static TableName get(int value)
  {
    switch (value)
    {
      case MEDICAL_RECORD_VALUE: return MEDICAL_RECORD;
      case PATIENT_MONITORING_VALUE: return PATIENT_MONITORING;
      case PRESCRIPTION_VALUE: return PRESCRIPTION;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private TableName(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //TableName
