/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Variable Prescription</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see ase.queryDsl.QueryDslPackage#getVariablePrescription()
 * @model
 * @generated
 */
public enum VariablePrescription implements Enumerator
{
  /**
   * The '<em><b>Prescription Id</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PRESCRIPTION_ID_VALUE
   * @generated
   * @ordered
   */
  PRESCRIPTION_ID(0, "prescriptionId", "prescriptionId"),

  /**
   * The '<em><b>Record Id</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RECORD_ID_VALUE
   * @generated
   * @ordered
   */
  RECORD_ID(1, "recordId", "recordId"),

  /**
   * The '<em><b>Medication Name</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MEDICATION_NAME_VALUE
   * @generated
   * @ordered
   */
  MEDICATION_NAME(2, "medicationName", "medicationName"),

  /**
   * The '<em><b>Start</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #START_VALUE
   * @generated
   * @ordered
   */
  START(3, "start", "start"),

  /**
   * The '<em><b>End</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #END_VALUE
   * @generated
   * @ordered
   */
  END(4, "end", "end"),

  /**
   * The '<em><b>Ordered</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ORDERED_VALUE
   * @generated
   * @ordered
   */
  ORDERED(5, "ordered", "ordered"),

  /**
   * The '<em><b>Price</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PRICE_VALUE
   * @generated
   * @ordered
   */
  PRICE(6, "price", "price");

  /**
   * The '<em><b>Prescription Id</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Prescription Id</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #PRESCRIPTION_ID
   * @model name="prescriptionId"
   * @generated
   * @ordered
   */
  public static final int PRESCRIPTION_ID_VALUE = 0;

  /**
   * The '<em><b>Record Id</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Record Id</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #RECORD_ID
   * @model name="recordId"
   * @generated
   * @ordered
   */
  public static final int RECORD_ID_VALUE = 1;

  /**
   * The '<em><b>Medication Name</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Medication Name</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MEDICATION_NAME
   * @model name="medicationName"
   * @generated
   * @ordered
   */
  public static final int MEDICATION_NAME_VALUE = 2;

  /**
   * The '<em><b>Start</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Start</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #START
   * @model name="start"
   * @generated
   * @ordered
   */
  public static final int START_VALUE = 3;

  /**
   * The '<em><b>End</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>End</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #END
   * @model name="end"
   * @generated
   * @ordered
   */
  public static final int END_VALUE = 4;

  /**
   * The '<em><b>Ordered</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Ordered</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ORDERED
   * @model name="ordered"
   * @generated
   * @ordered
   */
  public static final int ORDERED_VALUE = 5;

  /**
   * The '<em><b>Price</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Price</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #PRICE
   * @model name="price"
   * @generated
   * @ordered
   */
  public static final int PRICE_VALUE = 6;

  /**
   * An array of all the '<em><b>Variable Prescription</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final VariablePrescription[] VALUES_ARRAY =
    new VariablePrescription[]
    {
      PRESCRIPTION_ID,
      RECORD_ID,
      MEDICATION_NAME,
      START,
      END,
      ORDERED,
      PRICE,
    };

  /**
   * A public read-only list of all the '<em><b>Variable Prescription</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<VariablePrescription> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Variable Prescription</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static VariablePrescription get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      VariablePrescription result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Variable Prescription</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static VariablePrescription getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      VariablePrescription result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Variable Prescription</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static VariablePrescription get(int value)
  {
    switch (value)
    {
      case PRESCRIPTION_ID_VALUE: return PRESCRIPTION_ID;
      case RECORD_ID_VALUE: return RECORD_ID;
      case MEDICATION_NAME_VALUE: return MEDICATION_NAME;
      case START_VALUE: return START;
      case END_VALUE: return END;
      case ORDERED_VALUE: return ORDERED;
      case PRICE_VALUE: return PRICE;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private VariablePrescription(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //VariablePrescription
