/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Variable Patient Monitoring</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see ase.queryDsl.QueryDslPackage#getVariablePatientMonitoring()
 * @model
 * @generated
 */
public enum VariablePatientMonitoring implements Enumerator
{
  /**
   * The '<em><b>Monitoring Id</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MONITORING_ID_VALUE
   * @generated
   * @ordered
   */
  MONITORING_ID(0, "monitoringId", "monitoringId"),

  /**
   * The '<em><b>Patient Id</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PATIENT_ID_VALUE
   * @generated
   * @ordered
   */
  PATIENT_ID(1, "patientId", "patientId"),

  /**
   * The '<em><b>Category</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CATEGORY_VALUE
   * @generated
   * @ordered
   */
  CATEGORY(2, "category", "category"),

  /**
   * The '<em><b>Date</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DATE_VALUE
   * @generated
   * @ordered
   */
  DATE(3, "date", "date"),

  /**
   * The '<em><b>Risk Perception</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RISK_PERCEPTION_VALUE
   * @generated
   * @ordered
   */
  RISK_PERCEPTION(4, "riskPerception", "riskPerception"),

  /**
   * The '<em><b>Treated</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TREATED_VALUE
   * @generated
   * @ordered
   */
  TREATED(5, "treated", "treated"),

  /**
   * The '<em><b>Device Id</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DEVICE_ID_VALUE
   * @generated
   * @ordered
   */
  DEVICE_ID(6, "deviceId", "deviceId");

  /**
   * The '<em><b>Monitoring Id</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Monitoring Id</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MONITORING_ID
   * @model name="monitoringId"
   * @generated
   * @ordered
   */
  public static final int MONITORING_ID_VALUE = 0;

  /**
   * The '<em><b>Patient Id</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Patient Id</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #PATIENT_ID
   * @model name="patientId"
   * @generated
   * @ordered
   */
  public static final int PATIENT_ID_VALUE = 1;

  /**
   * The '<em><b>Category</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Category</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CATEGORY
   * @model name="category"
   * @generated
   * @ordered
   */
  public static final int CATEGORY_VALUE = 2;

  /**
   * The '<em><b>Date</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Date</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DATE
   * @model name="date"
   * @generated
   * @ordered
   */
  public static final int DATE_VALUE = 3;

  /**
   * The '<em><b>Risk Perception</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Risk Perception</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #RISK_PERCEPTION
   * @model name="riskPerception"
   * @generated
   * @ordered
   */
  public static final int RISK_PERCEPTION_VALUE = 4;

  /**
   * The '<em><b>Treated</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Treated</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TREATED
   * @model name="treated"
   * @generated
   * @ordered
   */
  public static final int TREATED_VALUE = 5;

  /**
   * The '<em><b>Device Id</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Device Id</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DEVICE_ID
   * @model name="deviceId"
   * @generated
   * @ordered
   */
  public static final int DEVICE_ID_VALUE = 6;

  /**
   * An array of all the '<em><b>Variable Patient Monitoring</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final VariablePatientMonitoring[] VALUES_ARRAY =
    new VariablePatientMonitoring[]
    {
      MONITORING_ID,
      PATIENT_ID,
      CATEGORY,
      DATE,
      RISK_PERCEPTION,
      TREATED,
      DEVICE_ID,
    };

  /**
   * A public read-only list of all the '<em><b>Variable Patient Monitoring</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<VariablePatientMonitoring> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Variable Patient Monitoring</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static VariablePatientMonitoring get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      VariablePatientMonitoring result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Variable Patient Monitoring</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static VariablePatientMonitoring getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      VariablePatientMonitoring result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Variable Patient Monitoring</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static VariablePatientMonitoring get(int value)
  {
    switch (value)
    {
      case MONITORING_ID_VALUE: return MONITORING_ID;
      case PATIENT_ID_VALUE: return PATIENT_ID;
      case CATEGORY_VALUE: return CATEGORY;
      case DATE_VALUE: return DATE;
      case RISK_PERCEPTION_VALUE: return RISK_PERCEPTION;
      case TREATED_VALUE: return TREATED;
      case DEVICE_ID_VALUE: return DEVICE_ID;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private VariablePatientMonitoring(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //VariablePatientMonitoring
