/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Where Prescription</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ase.queryDsl.WherePrescription#getPrescriptionId <em>Prescription Id</em>}</li>
 *   <li>{@link ase.queryDsl.WherePrescription#getRecordId <em>Record Id</em>}</li>
 *   <li>{@link ase.queryDsl.WherePrescription#getMedicationName <em>Medication Name</em>}</li>
 *   <li>{@link ase.queryDsl.WherePrescription#getStart <em>Start</em>}</li>
 *   <li>{@link ase.queryDsl.WherePrescription#getEnd <em>End</em>}</li>
 *   <li>{@link ase.queryDsl.WherePrescription#getOrdered <em>Ordered</em>}</li>
 *   <li>{@link ase.queryDsl.WherePrescription#getPrice <em>Price</em>}</li>
 * </ul>
 *
 * @see ase.queryDsl.QueryDslPackage#getWherePrescription()
 * @model
 * @generated
 */
public interface WherePrescription extends EObject
{
  /**
   * Returns the value of the '<em><b>Prescription Id</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Integer}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prescription Id</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prescription Id</em>' attribute list.
   * @see ase.queryDsl.QueryDslPackage#getWherePrescription_PrescriptionId()
   * @model unique="false"
   * @generated
   */
  EList<Integer> getPrescriptionId();

  /**
   * Returns the value of the '<em><b>Record Id</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Integer}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Record Id</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Record Id</em>' attribute list.
   * @see ase.queryDsl.QueryDslPackage#getWherePrescription_RecordId()
   * @model unique="false"
   * @generated
   */
  EList<Integer> getRecordId();

  /**
   * Returns the value of the '<em><b>Medication Name</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Medication Name</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Medication Name</em>' attribute list.
   * @see ase.queryDsl.QueryDslPackage#getWherePrescription_MedicationName()
   * @model unique="false"
   * @generated
   */
  EList<String> getMedicationName();

  /**
   * Returns the value of the '<em><b>Start</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Start</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start</em>' attribute list.
   * @see ase.queryDsl.QueryDslPackage#getWherePrescription_Start()
   * @model unique="false"
   * @generated
   */
  EList<String> getStart();

  /**
   * Returns the value of the '<em><b>End</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>End</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>End</em>' attribute list.
   * @see ase.queryDsl.QueryDslPackage#getWherePrescription_End()
   * @model unique="false"
   * @generated
   */
  EList<String> getEnd();

  /**
   * Returns the value of the '<em><b>Ordered</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ordered</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ordered</em>' attribute list.
   * @see ase.queryDsl.QueryDslPackage#getWherePrescription_Ordered()
   * @model unique="false"
   * @generated
   */
  EList<String> getOrdered();

  /**
   * Returns the value of the '<em><b>Price</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Price</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Price</em>' attribute list.
   * @see ase.queryDsl.QueryDslPackage#getWherePrescription_Price()
   * @model unique="false"
   * @generated
   */
  EList<String> getPrice();

} // WherePrescription
