/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Where Medical Record</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ase.queryDsl.WhereMedicalRecord#getRecordId <em>Record Id</em>}</li>
 *   <li>{@link ase.queryDsl.WhereMedicalRecord#getPatientId <em>Patient Id</em>}</li>
 *   <li>{@link ase.queryDsl.WhereMedicalRecord#getDoctorId <em>Doctor Id</em>}</li>
 *   <li>{@link ase.queryDsl.WhereMedicalRecord#getMedicalCondition <em>Medical Condition</em>}</li>
 *   <li>{@link ase.queryDsl.WhereMedicalRecord#getDate <em>Date</em>}</li>
 *   <li>{@link ase.queryDsl.WhereMedicalRecord#getPrice <em>Price</em>}</li>
 *   <li>{@link ase.queryDsl.WhereMedicalRecord#getDescription <em>Description</em>}</li>
 * </ul>
 *
 * @see ase.queryDsl.QueryDslPackage#getWhereMedicalRecord()
 * @model
 * @generated
 */
public interface WhereMedicalRecord extends EObject
{
  /**
   * Returns the value of the '<em><b>Record Id</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Integer}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Record Id</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Record Id</em>' attribute list.
   * @see ase.queryDsl.QueryDslPackage#getWhereMedicalRecord_RecordId()
   * @model unique="false"
   * @generated
   */
  EList<Integer> getRecordId();

  /**
   * Returns the value of the '<em><b>Patient Id</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Integer}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Patient Id</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Patient Id</em>' attribute list.
   * @see ase.queryDsl.QueryDslPackage#getWhereMedicalRecord_PatientId()
   * @model unique="false"
   * @generated
   */
  EList<Integer> getPatientId();

  /**
   * Returns the value of the '<em><b>Doctor Id</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Integer}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Doctor Id</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Doctor Id</em>' attribute list.
   * @see ase.queryDsl.QueryDslPackage#getWhereMedicalRecord_DoctorId()
   * @model unique="false"
   * @generated
   */
  EList<Integer> getDoctorId();

  /**
   * Returns the value of the '<em><b>Medical Condition</b></em>' attribute list.
   * The list contents are of type {@link ase.queryDsl.MedicalCondition}.
   * The literals are from the enumeration {@link ase.queryDsl.MedicalCondition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Medical Condition</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Medical Condition</em>' attribute list.
   * @see ase.queryDsl.MedicalCondition
   * @see ase.queryDsl.QueryDslPackage#getWhereMedicalRecord_MedicalCondition()
   * @model unique="false"
   * @generated
   */
  EList<MedicalCondition> getMedicalCondition();

  /**
   * Returns the value of the '<em><b>Date</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Date</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Date</em>' attribute list.
   * @see ase.queryDsl.QueryDslPackage#getWhereMedicalRecord_Date()
   * @model unique="false"
   * @generated
   */
  EList<String> getDate();

  /**
   * Returns the value of the '<em><b>Price</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Price</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Price</em>' attribute list.
   * @see ase.queryDsl.QueryDslPackage#getWhereMedicalRecord_Price()
   * @model unique="false"
   * @generated
   */
  EList<String> getPrice();

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute list.
   * @see ase.queryDsl.QueryDslPackage#getWhereMedicalRecord_Description()
   * @model unique="false"
   * @generated
   */
  EList<String> getDescription();

} // WhereMedicalRecord
