/*
 * generated by Xtext 2.12.0.M1
 */
package ase.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class QueryDslScopeProvider extends AbstractQueryDslScopeProvider {

}
