/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl.impl;

import ase.queryDsl.DeleteMedicalRecord;
import ase.queryDsl.QueryDslPackage;
import ase.queryDsl.WhereMedicalRecord;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Delete Medical Record</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ase.queryDsl.impl.DeleteMedicalRecordImpl#getWhereMedicalRecord <em>Where Medical Record</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DeleteMedicalRecordImpl extends DeleteImpl implements DeleteMedicalRecord
{
  /**
   * The cached value of the '{@link #getWhereMedicalRecord() <em>Where Medical Record</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWhereMedicalRecord()
   * @generated
   * @ordered
   */
  protected EList<WhereMedicalRecord> whereMedicalRecord;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DeleteMedicalRecordImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QueryDslPackage.Literals.DELETE_MEDICAL_RECORD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<WhereMedicalRecord> getWhereMedicalRecord()
  {
    if (whereMedicalRecord == null)
    {
      whereMedicalRecord = new EObjectContainmentEList<WhereMedicalRecord>(WhereMedicalRecord.class, this, QueryDslPackage.DELETE_MEDICAL_RECORD__WHERE_MEDICAL_RECORD);
    }
    return whereMedicalRecord;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QueryDslPackage.DELETE_MEDICAL_RECORD__WHERE_MEDICAL_RECORD:
        return ((InternalEList<?>)getWhereMedicalRecord()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QueryDslPackage.DELETE_MEDICAL_RECORD__WHERE_MEDICAL_RECORD:
        return getWhereMedicalRecord();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QueryDslPackage.DELETE_MEDICAL_RECORD__WHERE_MEDICAL_RECORD:
        getWhereMedicalRecord().clear();
        getWhereMedicalRecord().addAll((Collection<? extends WhereMedicalRecord>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QueryDslPackage.DELETE_MEDICAL_RECORD__WHERE_MEDICAL_RECORD:
        getWhereMedicalRecord().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QueryDslPackage.DELETE_MEDICAL_RECORD__WHERE_MEDICAL_RECORD:
        return whereMedicalRecord != null && !whereMedicalRecord.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //DeleteMedicalRecordImpl
