/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl.impl;

import ase.queryDsl.DeletePatientMonitoring;
import ase.queryDsl.QueryDslPackage;
import ase.queryDsl.WherePatientMonitoring;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Delete Patient Monitoring</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ase.queryDsl.impl.DeletePatientMonitoringImpl#getWherepatientMonitoring <em>Wherepatient Monitoring</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DeletePatientMonitoringImpl extends DeleteImpl implements DeletePatientMonitoring
{
  /**
   * The cached value of the '{@link #getWherepatientMonitoring() <em>Wherepatient Monitoring</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWherepatientMonitoring()
   * @generated
   * @ordered
   */
  protected EList<WherePatientMonitoring> wherepatientMonitoring;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DeletePatientMonitoringImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QueryDslPackage.Literals.DELETE_PATIENT_MONITORING;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<WherePatientMonitoring> getWherepatientMonitoring()
  {
    if (wherepatientMonitoring == null)
    {
      wherepatientMonitoring = new EObjectContainmentEList<WherePatientMonitoring>(WherePatientMonitoring.class, this, QueryDslPackage.DELETE_PATIENT_MONITORING__WHEREPATIENT_MONITORING);
    }
    return wherepatientMonitoring;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QueryDslPackage.DELETE_PATIENT_MONITORING__WHEREPATIENT_MONITORING:
        return ((InternalEList<?>)getWherepatientMonitoring()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QueryDslPackage.DELETE_PATIENT_MONITORING__WHEREPATIENT_MONITORING:
        return getWherepatientMonitoring();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QueryDslPackage.DELETE_PATIENT_MONITORING__WHEREPATIENT_MONITORING:
        getWherepatientMonitoring().clear();
        getWherepatientMonitoring().addAll((Collection<? extends WherePatientMonitoring>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QueryDslPackage.DELETE_PATIENT_MONITORING__WHEREPATIENT_MONITORING:
        getWherepatientMonitoring().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QueryDslPackage.DELETE_PATIENT_MONITORING__WHEREPATIENT_MONITORING:
        return wherepatientMonitoring != null && !wherepatientMonitoring.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //DeletePatientMonitoringImpl
