/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl.impl;

import ase.queryDsl.InsertPatientMonitoring;
import ase.queryDsl.MedicalCondition;
import ase.queryDsl.QueryDslPackage;
import ase.queryDsl.RiskPerception;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Insert Patient Monitoring</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ase.queryDsl.impl.InsertPatientMonitoringImpl#getMonitoringId <em>Monitoring Id</em>}</li>
 *   <li>{@link ase.queryDsl.impl.InsertPatientMonitoringImpl#getPatientId <em>Patient Id</em>}</li>
 *   <li>{@link ase.queryDsl.impl.InsertPatientMonitoringImpl#getCategory <em>Category</em>}</li>
 *   <li>{@link ase.queryDsl.impl.InsertPatientMonitoringImpl#getDate <em>Date</em>}</li>
 *   <li>{@link ase.queryDsl.impl.InsertPatientMonitoringImpl#getRiskPerception <em>Risk Perception</em>}</li>
 *   <li>{@link ase.queryDsl.impl.InsertPatientMonitoringImpl#getTreadted <em>Treadted</em>}</li>
 *   <li>{@link ase.queryDsl.impl.InsertPatientMonitoringImpl#getDeviceId <em>Device Id</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InsertPatientMonitoringImpl extends InsertImpl implements InsertPatientMonitoring
{
  /**
   * The default value of the '{@link #getMonitoringId() <em>Monitoring Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMonitoringId()
   * @generated
   * @ordered
   */
  protected static final int MONITORING_ID_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getMonitoringId() <em>Monitoring Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMonitoringId()
   * @generated
   * @ordered
   */
  protected int monitoringId = MONITORING_ID_EDEFAULT;

  /**
   * The default value of the '{@link #getPatientId() <em>Patient Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPatientId()
   * @generated
   * @ordered
   */
  protected static final int PATIENT_ID_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPatientId() <em>Patient Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPatientId()
   * @generated
   * @ordered
   */
  protected int patientId = PATIENT_ID_EDEFAULT;

  /**
   * The default value of the '{@link #getCategory() <em>Category</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCategory()
   * @generated
   * @ordered
   */
  protected static final MedicalCondition CATEGORY_EDEFAULT = MedicalCondition.BRONCHITIS;

  /**
   * The cached value of the '{@link #getCategory() <em>Category</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCategory()
   * @generated
   * @ordered
   */
  protected MedicalCondition category = CATEGORY_EDEFAULT;

  /**
   * The default value of the '{@link #getDate() <em>Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDate()
   * @generated
   * @ordered
   */
  protected static final String DATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDate() <em>Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDate()
   * @generated
   * @ordered
   */
  protected String date = DATE_EDEFAULT;

  /**
   * The default value of the '{@link #getRiskPerception() <em>Risk Perception</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRiskPerception()
   * @generated
   * @ordered
   */
  protected static final RiskPerception RISK_PERCEPTION_EDEFAULT = RiskPerception.HIGH;

  /**
   * The cached value of the '{@link #getRiskPerception() <em>Risk Perception</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRiskPerception()
   * @generated
   * @ordered
   */
  protected RiskPerception riskPerception = RISK_PERCEPTION_EDEFAULT;

  /**
   * The default value of the '{@link #getTreadted() <em>Treadted</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTreadted()
   * @generated
   * @ordered
   */
  protected static final String TREADTED_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTreadted() <em>Treadted</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTreadted()
   * @generated
   * @ordered
   */
  protected String treadted = TREADTED_EDEFAULT;

  /**
   * The default value of the '{@link #getDeviceId() <em>Device Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeviceId()
   * @generated
   * @ordered
   */
  protected static final int DEVICE_ID_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getDeviceId() <em>Device Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeviceId()
   * @generated
   * @ordered
   */
  protected int deviceId = DEVICE_ID_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InsertPatientMonitoringImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QueryDslPackage.Literals.INSERT_PATIENT_MONITORING;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getMonitoringId()
  {
    return monitoringId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMonitoringId(int newMonitoringId)
  {
    int oldMonitoringId = monitoringId;
    monitoringId = newMonitoringId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.INSERT_PATIENT_MONITORING__MONITORING_ID, oldMonitoringId, monitoringId));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getPatientId()
  {
    return patientId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPatientId(int newPatientId)
  {
    int oldPatientId = patientId;
    patientId = newPatientId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.INSERT_PATIENT_MONITORING__PATIENT_ID, oldPatientId, patientId));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MedicalCondition getCategory()
  {
    return category;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCategory(MedicalCondition newCategory)
  {
    MedicalCondition oldCategory = category;
    category = newCategory == null ? CATEGORY_EDEFAULT : newCategory;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.INSERT_PATIENT_MONITORING__CATEGORY, oldCategory, category));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDate()
  {
    return date;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDate(String newDate)
  {
    String oldDate = date;
    date = newDate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.INSERT_PATIENT_MONITORING__DATE, oldDate, date));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RiskPerception getRiskPerception()
  {
    return riskPerception;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRiskPerception(RiskPerception newRiskPerception)
  {
    RiskPerception oldRiskPerception = riskPerception;
    riskPerception = newRiskPerception == null ? RISK_PERCEPTION_EDEFAULT : newRiskPerception;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.INSERT_PATIENT_MONITORING__RISK_PERCEPTION, oldRiskPerception, riskPerception));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTreadted()
  {
    return treadted;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTreadted(String newTreadted)
  {
    String oldTreadted = treadted;
    treadted = newTreadted;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.INSERT_PATIENT_MONITORING__TREADTED, oldTreadted, treadted));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getDeviceId()
  {
    return deviceId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDeviceId(int newDeviceId)
  {
    int oldDeviceId = deviceId;
    deviceId = newDeviceId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.INSERT_PATIENT_MONITORING__DEVICE_ID, oldDeviceId, deviceId));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QueryDslPackage.INSERT_PATIENT_MONITORING__MONITORING_ID:
        return getMonitoringId();
      case QueryDslPackage.INSERT_PATIENT_MONITORING__PATIENT_ID:
        return getPatientId();
      case QueryDslPackage.INSERT_PATIENT_MONITORING__CATEGORY:
        return getCategory();
      case QueryDslPackage.INSERT_PATIENT_MONITORING__DATE:
        return getDate();
      case QueryDslPackage.INSERT_PATIENT_MONITORING__RISK_PERCEPTION:
        return getRiskPerception();
      case QueryDslPackage.INSERT_PATIENT_MONITORING__TREADTED:
        return getTreadted();
      case QueryDslPackage.INSERT_PATIENT_MONITORING__DEVICE_ID:
        return getDeviceId();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QueryDslPackage.INSERT_PATIENT_MONITORING__MONITORING_ID:
        setMonitoringId((Integer)newValue);
        return;
      case QueryDslPackage.INSERT_PATIENT_MONITORING__PATIENT_ID:
        setPatientId((Integer)newValue);
        return;
      case QueryDslPackage.INSERT_PATIENT_MONITORING__CATEGORY:
        setCategory((MedicalCondition)newValue);
        return;
      case QueryDslPackage.INSERT_PATIENT_MONITORING__DATE:
        setDate((String)newValue);
        return;
      case QueryDslPackage.INSERT_PATIENT_MONITORING__RISK_PERCEPTION:
        setRiskPerception((RiskPerception)newValue);
        return;
      case QueryDslPackage.INSERT_PATIENT_MONITORING__TREADTED:
        setTreadted((String)newValue);
        return;
      case QueryDslPackage.INSERT_PATIENT_MONITORING__DEVICE_ID:
        setDeviceId((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QueryDslPackage.INSERT_PATIENT_MONITORING__MONITORING_ID:
        setMonitoringId(MONITORING_ID_EDEFAULT);
        return;
      case QueryDslPackage.INSERT_PATIENT_MONITORING__PATIENT_ID:
        setPatientId(PATIENT_ID_EDEFAULT);
        return;
      case QueryDslPackage.INSERT_PATIENT_MONITORING__CATEGORY:
        setCategory(CATEGORY_EDEFAULT);
        return;
      case QueryDslPackage.INSERT_PATIENT_MONITORING__DATE:
        setDate(DATE_EDEFAULT);
        return;
      case QueryDslPackage.INSERT_PATIENT_MONITORING__RISK_PERCEPTION:
        setRiskPerception(RISK_PERCEPTION_EDEFAULT);
        return;
      case QueryDslPackage.INSERT_PATIENT_MONITORING__TREADTED:
        setTreadted(TREADTED_EDEFAULT);
        return;
      case QueryDslPackage.INSERT_PATIENT_MONITORING__DEVICE_ID:
        setDeviceId(DEVICE_ID_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QueryDslPackage.INSERT_PATIENT_MONITORING__MONITORING_ID:
        return monitoringId != MONITORING_ID_EDEFAULT;
      case QueryDslPackage.INSERT_PATIENT_MONITORING__PATIENT_ID:
        return patientId != PATIENT_ID_EDEFAULT;
      case QueryDslPackage.INSERT_PATIENT_MONITORING__CATEGORY:
        return category != CATEGORY_EDEFAULT;
      case QueryDslPackage.INSERT_PATIENT_MONITORING__DATE:
        return DATE_EDEFAULT == null ? date != null : !DATE_EDEFAULT.equals(date);
      case QueryDslPackage.INSERT_PATIENT_MONITORING__RISK_PERCEPTION:
        return riskPerception != RISK_PERCEPTION_EDEFAULT;
      case QueryDslPackage.INSERT_PATIENT_MONITORING__TREADTED:
        return TREADTED_EDEFAULT == null ? treadted != null : !TREADTED_EDEFAULT.equals(treadted);
      case QueryDslPackage.INSERT_PATIENT_MONITORING__DEVICE_ID:
        return deviceId != DEVICE_ID_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (monitoringId: ");
    result.append(monitoringId);
    result.append(", patientId: ");
    result.append(patientId);
    result.append(", category: ");
    result.append(category);
    result.append(", date: ");
    result.append(date);
    result.append(", riskPerception: ");
    result.append(riskPerception);
    result.append(", treadted: ");
    result.append(treadted);
    result.append(", deviceId: ");
    result.append(deviceId);
    result.append(')');
    return result.toString();
  }

} //InsertPatientMonitoringImpl
