/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl.impl;

import ase.queryDsl.InsertPrescription;
import ase.queryDsl.QueryDslPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Insert Prescription</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ase.queryDsl.impl.InsertPrescriptionImpl#getPrescriptionId <em>Prescription Id</em>}</li>
 *   <li>{@link ase.queryDsl.impl.InsertPrescriptionImpl#getRecordId <em>Record Id</em>}</li>
 *   <li>{@link ase.queryDsl.impl.InsertPrescriptionImpl#getMedicationName <em>Medication Name</em>}</li>
 *   <li>{@link ase.queryDsl.impl.InsertPrescriptionImpl#getStart <em>Start</em>}</li>
 *   <li>{@link ase.queryDsl.impl.InsertPrescriptionImpl#getEnd <em>End</em>}</li>
 *   <li>{@link ase.queryDsl.impl.InsertPrescriptionImpl#getOrdered <em>Ordered</em>}</li>
 *   <li>{@link ase.queryDsl.impl.InsertPrescriptionImpl#getPrice <em>Price</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InsertPrescriptionImpl extends InsertImpl implements InsertPrescription
{
  /**
   * The default value of the '{@link #getPrescriptionId() <em>Prescription Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrescriptionId()
   * @generated
   * @ordered
   */
  protected static final int PRESCRIPTION_ID_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPrescriptionId() <em>Prescription Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrescriptionId()
   * @generated
   * @ordered
   */
  protected int prescriptionId = PRESCRIPTION_ID_EDEFAULT;

  /**
   * The default value of the '{@link #getRecordId() <em>Record Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRecordId()
   * @generated
   * @ordered
   */
  protected static final int RECORD_ID_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getRecordId() <em>Record Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRecordId()
   * @generated
   * @ordered
   */
  protected int recordId = RECORD_ID_EDEFAULT;

  /**
   * The default value of the '{@link #getMedicationName() <em>Medication Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMedicationName()
   * @generated
   * @ordered
   */
  protected static final String MEDICATION_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMedicationName() <em>Medication Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMedicationName()
   * @generated
   * @ordered
   */
  protected String medicationName = MEDICATION_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getStart() <em>Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStart()
   * @generated
   * @ordered
   */
  protected static final String START_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStart() <em>Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStart()
   * @generated
   * @ordered
   */
  protected String start = START_EDEFAULT;

  /**
   * The default value of the '{@link #getEnd() <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnd()
   * @generated
   * @ordered
   */
  protected static final String END_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEnd() <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnd()
   * @generated
   * @ordered
   */
  protected String end = END_EDEFAULT;

  /**
   * The default value of the '{@link #getOrdered() <em>Ordered</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOrdered()
   * @generated
   * @ordered
   */
  protected static final String ORDERED_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOrdered() <em>Ordered</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOrdered()
   * @generated
   * @ordered
   */
  protected String ordered = ORDERED_EDEFAULT;

  /**
   * The default value of the '{@link #getPrice() <em>Price</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrice()
   * @generated
   * @ordered
   */
  protected static final String PRICE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPrice() <em>Price</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrice()
   * @generated
   * @ordered
   */
  protected String price = PRICE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InsertPrescriptionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QueryDslPackage.Literals.INSERT_PRESCRIPTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getPrescriptionId()
  {
    return prescriptionId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPrescriptionId(int newPrescriptionId)
  {
    int oldPrescriptionId = prescriptionId;
    prescriptionId = newPrescriptionId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.INSERT_PRESCRIPTION__PRESCRIPTION_ID, oldPrescriptionId, prescriptionId));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getRecordId()
  {
    return recordId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRecordId(int newRecordId)
  {
    int oldRecordId = recordId;
    recordId = newRecordId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.INSERT_PRESCRIPTION__RECORD_ID, oldRecordId, recordId));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getMedicationName()
  {
    return medicationName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMedicationName(String newMedicationName)
  {
    String oldMedicationName = medicationName;
    medicationName = newMedicationName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.INSERT_PRESCRIPTION__MEDICATION_NAME, oldMedicationName, medicationName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getStart()
  {
    return start;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStart(String newStart)
  {
    String oldStart = start;
    start = newStart;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.INSERT_PRESCRIPTION__START, oldStart, start));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getEnd()
  {
    return end;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEnd(String newEnd)
  {
    String oldEnd = end;
    end = newEnd;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.INSERT_PRESCRIPTION__END, oldEnd, end));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getOrdered()
  {
    return ordered;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOrdered(String newOrdered)
  {
    String oldOrdered = ordered;
    ordered = newOrdered;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.INSERT_PRESCRIPTION__ORDERED, oldOrdered, ordered));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPrice()
  {
    return price;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPrice(String newPrice)
  {
    String oldPrice = price;
    price = newPrice;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QueryDslPackage.INSERT_PRESCRIPTION__PRICE, oldPrice, price));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QueryDslPackage.INSERT_PRESCRIPTION__PRESCRIPTION_ID:
        return getPrescriptionId();
      case QueryDslPackage.INSERT_PRESCRIPTION__RECORD_ID:
        return getRecordId();
      case QueryDslPackage.INSERT_PRESCRIPTION__MEDICATION_NAME:
        return getMedicationName();
      case QueryDslPackage.INSERT_PRESCRIPTION__START:
        return getStart();
      case QueryDslPackage.INSERT_PRESCRIPTION__END:
        return getEnd();
      case QueryDslPackage.INSERT_PRESCRIPTION__ORDERED:
        return getOrdered();
      case QueryDslPackage.INSERT_PRESCRIPTION__PRICE:
        return getPrice();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QueryDslPackage.INSERT_PRESCRIPTION__PRESCRIPTION_ID:
        setPrescriptionId((Integer)newValue);
        return;
      case QueryDslPackage.INSERT_PRESCRIPTION__RECORD_ID:
        setRecordId((Integer)newValue);
        return;
      case QueryDslPackage.INSERT_PRESCRIPTION__MEDICATION_NAME:
        setMedicationName((String)newValue);
        return;
      case QueryDslPackage.INSERT_PRESCRIPTION__START:
        setStart((String)newValue);
        return;
      case QueryDslPackage.INSERT_PRESCRIPTION__END:
        setEnd((String)newValue);
        return;
      case QueryDslPackage.INSERT_PRESCRIPTION__ORDERED:
        setOrdered((String)newValue);
        return;
      case QueryDslPackage.INSERT_PRESCRIPTION__PRICE:
        setPrice((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QueryDslPackage.INSERT_PRESCRIPTION__PRESCRIPTION_ID:
        setPrescriptionId(PRESCRIPTION_ID_EDEFAULT);
        return;
      case QueryDslPackage.INSERT_PRESCRIPTION__RECORD_ID:
        setRecordId(RECORD_ID_EDEFAULT);
        return;
      case QueryDslPackage.INSERT_PRESCRIPTION__MEDICATION_NAME:
        setMedicationName(MEDICATION_NAME_EDEFAULT);
        return;
      case QueryDslPackage.INSERT_PRESCRIPTION__START:
        setStart(START_EDEFAULT);
        return;
      case QueryDslPackage.INSERT_PRESCRIPTION__END:
        setEnd(END_EDEFAULT);
        return;
      case QueryDslPackage.INSERT_PRESCRIPTION__ORDERED:
        setOrdered(ORDERED_EDEFAULT);
        return;
      case QueryDslPackage.INSERT_PRESCRIPTION__PRICE:
        setPrice(PRICE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QueryDslPackage.INSERT_PRESCRIPTION__PRESCRIPTION_ID:
        return prescriptionId != PRESCRIPTION_ID_EDEFAULT;
      case QueryDslPackage.INSERT_PRESCRIPTION__RECORD_ID:
        return recordId != RECORD_ID_EDEFAULT;
      case QueryDslPackage.INSERT_PRESCRIPTION__MEDICATION_NAME:
        return MEDICATION_NAME_EDEFAULT == null ? medicationName != null : !MEDICATION_NAME_EDEFAULT.equals(medicationName);
      case QueryDslPackage.INSERT_PRESCRIPTION__START:
        return START_EDEFAULT == null ? start != null : !START_EDEFAULT.equals(start);
      case QueryDslPackage.INSERT_PRESCRIPTION__END:
        return END_EDEFAULT == null ? end != null : !END_EDEFAULT.equals(end);
      case QueryDslPackage.INSERT_PRESCRIPTION__ORDERED:
        return ORDERED_EDEFAULT == null ? ordered != null : !ORDERED_EDEFAULT.equals(ordered);
      case QueryDslPackage.INSERT_PRESCRIPTION__PRICE:
        return PRICE_EDEFAULT == null ? price != null : !PRICE_EDEFAULT.equals(price);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (prescriptionId: ");
    result.append(prescriptionId);
    result.append(", recordId: ");
    result.append(recordId);
    result.append(", medicationName: ");
    result.append(medicationName);
    result.append(", start: ");
    result.append(start);
    result.append(", end: ");
    result.append(end);
    result.append(", ordered: ");
    result.append(ordered);
    result.append(", price: ");
    result.append(price);
    result.append(')');
    return result.toString();
  }

} //InsertPrescriptionImpl
