/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl.impl;

import ase.queryDsl.MedicalCondition;
import ase.queryDsl.QueryDslPackage;
import ase.queryDsl.WhereMedicalRecord;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Where Medical Record</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ase.queryDsl.impl.WhereMedicalRecordImpl#getRecordId <em>Record Id</em>}</li>
 *   <li>{@link ase.queryDsl.impl.WhereMedicalRecordImpl#getPatientId <em>Patient Id</em>}</li>
 *   <li>{@link ase.queryDsl.impl.WhereMedicalRecordImpl#getDoctorId <em>Doctor Id</em>}</li>
 *   <li>{@link ase.queryDsl.impl.WhereMedicalRecordImpl#getMedicalCondition <em>Medical Condition</em>}</li>
 *   <li>{@link ase.queryDsl.impl.WhereMedicalRecordImpl#getDate <em>Date</em>}</li>
 *   <li>{@link ase.queryDsl.impl.WhereMedicalRecordImpl#getPrice <em>Price</em>}</li>
 *   <li>{@link ase.queryDsl.impl.WhereMedicalRecordImpl#getDescription <em>Description</em>}</li>
 * </ul>
 *
 * @generated
 */
public class WhereMedicalRecordImpl extends MinimalEObjectImpl.Container implements WhereMedicalRecord
{
  /**
   * The cached value of the '{@link #getRecordId() <em>Record Id</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRecordId()
   * @generated
   * @ordered
   */
  protected EList<Integer> recordId;

  /**
   * The cached value of the '{@link #getPatientId() <em>Patient Id</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPatientId()
   * @generated
   * @ordered
   */
  protected EList<Integer> patientId;

  /**
   * The cached value of the '{@link #getDoctorId() <em>Doctor Id</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDoctorId()
   * @generated
   * @ordered
   */
  protected EList<Integer> doctorId;

  /**
   * The cached value of the '{@link #getMedicalCondition() <em>Medical Condition</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMedicalCondition()
   * @generated
   * @ordered
   */
  protected EList<MedicalCondition> medicalCondition;

  /**
   * The cached value of the '{@link #getDate() <em>Date</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDate()
   * @generated
   * @ordered
   */
  protected EList<String> date;

  /**
   * The cached value of the '{@link #getPrice() <em>Price</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrice()
   * @generated
   * @ordered
   */
  protected EList<String> price;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected EList<String> description;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WhereMedicalRecordImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QueryDslPackage.Literals.WHERE_MEDICAL_RECORD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Integer> getRecordId()
  {
    if (recordId == null)
    {
      recordId = new EDataTypeEList<Integer>(Integer.class, this, QueryDslPackage.WHERE_MEDICAL_RECORD__RECORD_ID);
    }
    return recordId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Integer> getPatientId()
  {
    if (patientId == null)
    {
      patientId = new EDataTypeEList<Integer>(Integer.class, this, QueryDslPackage.WHERE_MEDICAL_RECORD__PATIENT_ID);
    }
    return patientId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Integer> getDoctorId()
  {
    if (doctorId == null)
    {
      doctorId = new EDataTypeEList<Integer>(Integer.class, this, QueryDslPackage.WHERE_MEDICAL_RECORD__DOCTOR_ID);
    }
    return doctorId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<MedicalCondition> getMedicalCondition()
  {
    if (medicalCondition == null)
    {
      medicalCondition = new EDataTypeEList<MedicalCondition>(MedicalCondition.class, this, QueryDslPackage.WHERE_MEDICAL_RECORD__MEDICAL_CONDITION);
    }
    return medicalCondition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getDate()
  {
    if (date == null)
    {
      date = new EDataTypeEList<String>(String.class, this, QueryDslPackage.WHERE_MEDICAL_RECORD__DATE);
    }
    return date;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getPrice()
  {
    if (price == null)
    {
      price = new EDataTypeEList<String>(String.class, this, QueryDslPackage.WHERE_MEDICAL_RECORD__PRICE);
    }
    return price;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getDescription()
  {
    if (description == null)
    {
      description = new EDataTypeEList<String>(String.class, this, QueryDslPackage.WHERE_MEDICAL_RECORD__DESCRIPTION);
    }
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QueryDslPackage.WHERE_MEDICAL_RECORD__RECORD_ID:
        return getRecordId();
      case QueryDslPackage.WHERE_MEDICAL_RECORD__PATIENT_ID:
        return getPatientId();
      case QueryDslPackage.WHERE_MEDICAL_RECORD__DOCTOR_ID:
        return getDoctorId();
      case QueryDslPackage.WHERE_MEDICAL_RECORD__MEDICAL_CONDITION:
        return getMedicalCondition();
      case QueryDslPackage.WHERE_MEDICAL_RECORD__DATE:
        return getDate();
      case QueryDslPackage.WHERE_MEDICAL_RECORD__PRICE:
        return getPrice();
      case QueryDslPackage.WHERE_MEDICAL_RECORD__DESCRIPTION:
        return getDescription();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QueryDslPackage.WHERE_MEDICAL_RECORD__RECORD_ID:
        getRecordId().clear();
        getRecordId().addAll((Collection<? extends Integer>)newValue);
        return;
      case QueryDslPackage.WHERE_MEDICAL_RECORD__PATIENT_ID:
        getPatientId().clear();
        getPatientId().addAll((Collection<? extends Integer>)newValue);
        return;
      case QueryDslPackage.WHERE_MEDICAL_RECORD__DOCTOR_ID:
        getDoctorId().clear();
        getDoctorId().addAll((Collection<? extends Integer>)newValue);
        return;
      case QueryDslPackage.WHERE_MEDICAL_RECORD__MEDICAL_CONDITION:
        getMedicalCondition().clear();
        getMedicalCondition().addAll((Collection<? extends MedicalCondition>)newValue);
        return;
      case QueryDslPackage.WHERE_MEDICAL_RECORD__DATE:
        getDate().clear();
        getDate().addAll((Collection<? extends String>)newValue);
        return;
      case QueryDslPackage.WHERE_MEDICAL_RECORD__PRICE:
        getPrice().clear();
        getPrice().addAll((Collection<? extends String>)newValue);
        return;
      case QueryDslPackage.WHERE_MEDICAL_RECORD__DESCRIPTION:
        getDescription().clear();
        getDescription().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QueryDslPackage.WHERE_MEDICAL_RECORD__RECORD_ID:
        getRecordId().clear();
        return;
      case QueryDslPackage.WHERE_MEDICAL_RECORD__PATIENT_ID:
        getPatientId().clear();
        return;
      case QueryDslPackage.WHERE_MEDICAL_RECORD__DOCTOR_ID:
        getDoctorId().clear();
        return;
      case QueryDslPackage.WHERE_MEDICAL_RECORD__MEDICAL_CONDITION:
        getMedicalCondition().clear();
        return;
      case QueryDslPackage.WHERE_MEDICAL_RECORD__DATE:
        getDate().clear();
        return;
      case QueryDslPackage.WHERE_MEDICAL_RECORD__PRICE:
        getPrice().clear();
        return;
      case QueryDslPackage.WHERE_MEDICAL_RECORD__DESCRIPTION:
        getDescription().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QueryDslPackage.WHERE_MEDICAL_RECORD__RECORD_ID:
        return recordId != null && !recordId.isEmpty();
      case QueryDslPackage.WHERE_MEDICAL_RECORD__PATIENT_ID:
        return patientId != null && !patientId.isEmpty();
      case QueryDslPackage.WHERE_MEDICAL_RECORD__DOCTOR_ID:
        return doctorId != null && !doctorId.isEmpty();
      case QueryDslPackage.WHERE_MEDICAL_RECORD__MEDICAL_CONDITION:
        return medicalCondition != null && !medicalCondition.isEmpty();
      case QueryDslPackage.WHERE_MEDICAL_RECORD__DATE:
        return date != null && !date.isEmpty();
      case QueryDslPackage.WHERE_MEDICAL_RECORD__PRICE:
        return price != null && !price.isEmpty();
      case QueryDslPackage.WHERE_MEDICAL_RECORD__DESCRIPTION:
        return description != null && !description.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (recordId: ");
    result.append(recordId);
    result.append(", patientId: ");
    result.append(patientId);
    result.append(", doctorId: ");
    result.append(doctorId);
    result.append(", medicalCondition: ");
    result.append(medicalCondition);
    result.append(", date: ");
    result.append(date);
    result.append(", price: ");
    result.append(price);
    result.append(", description: ");
    result.append(description);
    result.append(')');
    return result.toString();
  }

} //WhereMedicalRecordImpl
