/**
 * generated by Xtext 2.12.0.M1
 */
package ase;

import ase.QueryDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class QueryDslStandaloneSetup extends QueryDslStandaloneSetupGenerated {
  public static void doSetup() {
    new QueryDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
