/*
 * generated by Xtext 2.12.0.M1
 */
package ase.ui.tests;

import ase.QueryDsl.ui.internal.QueryDslActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class QueryDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return QueryDslActivator.getInstance().getInjector("ase.QueryDsl");
	}

}
