/*
 * generated by Xtext 2.12.0.M1
 */
package ase.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractQueryDslScopeProvider extends DelegatingScopeProvider {
}
