/*
 * generated by Xtext 2.12.0.M1
 */
package ase.ui;

import ase.QueryDsl.ui.internal.QueryDslActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class QueryDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return QueryDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return QueryDslActivator.getInstance().getInjector(QueryDslActivator.ASE_QUERYDSL);
	}
	
}
