/**
 * generated by Xtext 2.12.0.M1
 */
package ase.ide;

import ase.ide.AbstractQueryDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class QueryDslIdeModule extends AbstractQueryDslIdeModule {
}
