/**
 * generated by Xtext 2.12.0.M1
 */
package ase.ui;

import ase.ui.AbstractQueryDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class QueryDslUiModule extends AbstractQueryDslUiModule {
  public QueryDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
