/*
 * generated by Xtext 2.12.0.M1
 */
package ase


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class QueryDslRuntimeModule extends AbstractQueryDslRuntimeModule {
}
