/**
 * generated by Xtext 2.12.0.M1
 */
package ase.queryDsl.util;

import ase.queryDsl.*;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see ase.queryDsl.QueryDslPackage
 * @generated
 */
public class QueryDslSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static QueryDslPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public QueryDslSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = QueryDslPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case QueryDslPackage.MODEL:
      {
        Model model = (Model)theEObject;
        T result = caseModel(model);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case QueryDslPackage.QUERY_TYPE:
      {
        QueryType queryType = (QueryType)theEObject;
        T result = caseQueryType(queryType);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case QueryDslPackage.SELECT:
      {
        Select select = (Select)theEObject;
        T result = caseSelect(select);
        if (result == null) result = caseQueryType(select);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case QueryDslPackage.SELECT_MEDICAL_RECORD:
      {
        SelectMedicalRecord selectMedicalRecord = (SelectMedicalRecord)theEObject;
        T result = caseSelectMedicalRecord(selectMedicalRecord);
        if (result == null) result = caseSelect(selectMedicalRecord);
        if (result == null) result = caseQueryType(selectMedicalRecord);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case QueryDslPackage.SELECT_PATIENT_MONITORING:
      {
        SelectPatientMonitoring selectPatientMonitoring = (SelectPatientMonitoring)theEObject;
        T result = caseSelectPatientMonitoring(selectPatientMonitoring);
        if (result == null) result = caseSelect(selectPatientMonitoring);
        if (result == null) result = caseQueryType(selectPatientMonitoring);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case QueryDslPackage.SELECT_PRESCRIPTION:
      {
        SelectPrescription selectPrescription = (SelectPrescription)theEObject;
        T result = caseSelectPrescription(selectPrescription);
        if (result == null) result = caseSelect(selectPrescription);
        if (result == null) result = caseQueryType(selectPrescription);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case QueryDslPackage.INSERT:
      {
        Insert insert = (Insert)theEObject;
        T result = caseInsert(insert);
        if (result == null) result = caseQueryType(insert);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case QueryDslPackage.INSERT_MEDICAL_RECORD:
      {
        InsertMedicalRecord insertMedicalRecord = (InsertMedicalRecord)theEObject;
        T result = caseInsertMedicalRecord(insertMedicalRecord);
        if (result == null) result = caseInsert(insertMedicalRecord);
        if (result == null) result = caseQueryType(insertMedicalRecord);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case QueryDslPackage.INSERT_PATIENT_MONITORING:
      {
        InsertPatientMonitoring insertPatientMonitoring = (InsertPatientMonitoring)theEObject;
        T result = caseInsertPatientMonitoring(insertPatientMonitoring);
        if (result == null) result = caseInsert(insertPatientMonitoring);
        if (result == null) result = caseQueryType(insertPatientMonitoring);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case QueryDslPackage.INSERT_PRESCRIPTION:
      {
        InsertPrescription insertPrescription = (InsertPrescription)theEObject;
        T result = caseInsertPrescription(insertPrescription);
        if (result == null) result = caseInsert(insertPrescription);
        if (result == null) result = caseQueryType(insertPrescription);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case QueryDslPackage.DROP:
      {
        Drop drop = (Drop)theEObject;
        T result = caseDrop(drop);
        if (result == null) result = caseQueryType(drop);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case QueryDslPackage.DELETE:
      {
        Delete delete = (Delete)theEObject;
        T result = caseDelete(delete);
        if (result == null) result = caseQueryType(delete);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case QueryDslPackage.DELETE_MEDICAL_RECORD:
      {
        DeleteMedicalRecord deleteMedicalRecord = (DeleteMedicalRecord)theEObject;
        T result = caseDeleteMedicalRecord(deleteMedicalRecord);
        if (result == null) result = caseDelete(deleteMedicalRecord);
        if (result == null) result = caseQueryType(deleteMedicalRecord);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case QueryDslPackage.DELETE_PATIENT_MONITORING:
      {
        DeletePatientMonitoring deletePatientMonitoring = (DeletePatientMonitoring)theEObject;
        T result = caseDeletePatientMonitoring(deletePatientMonitoring);
        if (result == null) result = caseDelete(deletePatientMonitoring);
        if (result == null) result = caseQueryType(deletePatientMonitoring);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case QueryDslPackage.DELETE_PRESCRIPTION:
      {
        DeletePrescription deletePrescription = (DeletePrescription)theEObject;
        T result = caseDeletePrescription(deletePrescription);
        if (result == null) result = caseDelete(deletePrescription);
        if (result == null) result = caseQueryType(deletePrescription);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case QueryDslPackage.WHERE_MEDICAL_RECORD:
      {
        WhereMedicalRecord whereMedicalRecord = (WhereMedicalRecord)theEObject;
        T result = caseWhereMedicalRecord(whereMedicalRecord);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case QueryDslPackage.WHERE_PATIENT_MONITORING:
      {
        WherePatientMonitoring wherePatientMonitoring = (WherePatientMonitoring)theEObject;
        T result = caseWherePatientMonitoring(wherePatientMonitoring);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case QueryDslPackage.WHERE_PRESCRIPTION:
      {
        WherePrescription wherePrescription = (WherePrescription)theEObject;
        T result = caseWherePrescription(wherePrescription);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Model</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseModel(Model object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Query Type</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Query Type</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseQueryType(QueryType object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Select</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Select</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSelect(Select object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Select Medical Record</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Select Medical Record</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSelectMedicalRecord(SelectMedicalRecord object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Select Patient Monitoring</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Select Patient Monitoring</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSelectPatientMonitoring(SelectPatientMonitoring object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Select Prescription</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Select Prescription</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSelectPrescription(SelectPrescription object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Insert</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Insert</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseInsert(Insert object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Insert Medical Record</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Insert Medical Record</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseInsertMedicalRecord(InsertMedicalRecord object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Insert Patient Monitoring</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Insert Patient Monitoring</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseInsertPatientMonitoring(InsertPatientMonitoring object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Insert Prescription</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Insert Prescription</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseInsertPrescription(InsertPrescription object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Drop</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Drop</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDrop(Drop object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Delete</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Delete</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDelete(Delete object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Delete Medical Record</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Delete Medical Record</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDeleteMedicalRecord(DeleteMedicalRecord object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Delete Patient Monitoring</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Delete Patient Monitoring</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDeletePatientMonitoring(DeletePatientMonitoring object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Delete Prescription</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Delete Prescription</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDeletePrescription(DeletePrescription object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Where Medical Record</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Where Medical Record</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseWhereMedicalRecord(WhereMedicalRecord object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Where Patient Monitoring</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Where Patient Monitoring</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseWherePatientMonitoring(WherePatientMonitoring object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Where Prescription</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Where Prescription</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseWherePrescription(WherePrescription object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //QueryDslSwitch
